keycloak:
  auth:
    existingSecret: "keycloak"
  proxyAddressForwarding: true
  image:
    repository: mylesagray/keycloak-arm
    tag: 15.0.1
  ingress:
    enabled: true
    hostname: sso.apps.blah.cloud
    certManager: true
    ingressClassName: "traefik"
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls: true
  extraEnvVars:
    - name: KEYCLOAK_FRONTEND_URL
      value: https://sso.apps.blah.cloud/auth
    - KEYCLOAK_USER=user
    - KEYCLOAK_PASSWORD=testing
    - DB_VENDOR=postgres
  postgresql:
      image:
        repository: postgres
        tag: 13.3
      postgresqlDataDir: /data/pgdata
      persistence:
        mountPath: /data/
  keycloakConfigCli:
    enabled: true
    image:
      repository: adorsys/keycloak-config-cli
      tag: v4.2.1-rc0-15.0.1
    configuration:
      myrealm.yaml: |
        realm: myrealm
        enabled: true
        displayName: My Realm