keycloak:
  auth:
    existingSecret: "keycloak"
  proxyAddressForwarding: true
  image:
    repository: mylesagray/keycloak-arm
    tag: 15.0.1
  ingress:
    enabled: true
    hostname: sso.apps.blah.cloud
    certManager: true
    ingressClassName: "traefik"
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls: true
  extraEnvVars:
    - name: KEYCLOAK_FRONTEND_URL
      value: https://sso.apps.blah.cloud/auth
    - name: KEYCLOAK_USER
      value: user
    - name: KEYCLOAK_PASSWORD
      valueFrom:
        secretKeyRef:
          key: admin-password
          name: keycloak
    - name: DB_VENDOR
      value: postgres
    - name: DB_ADDR
      value: keycloak-postgresql
    - name: DB_PORT
      value: '5432'
    - name: DB_DATABASE
      value: bitnami_keycloak
    - name: DB_USER
      value: bn_keycloak
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: keycloak
  postgresql:
      image:
        repository: postgres
        tag: 13.3
      existingSecret: "keycloak-postgresql"
      postgresqlDataDir: /data/pgdata
      persistence:
        mountPath: /data/
  keycloakConfigCli:
    enabled: true
    image:
      repository: adorsys/keycloak-config-cli
      tag: v4.2.1-rc0-15.0.1
    configuration:
      myrealm.yaml: |
        realm: myrealm
        enabled: true
        displayName: My Realm