metallb:
  rbac:
    create: true
  prometheusRule:
    enabled: true
  controller:
    image:
      repository: metallb/controller
      tag: v0.11.0
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
    prometheus:
      serviceMonitor:
        enabled: true
  speaker:
    image:
      repository: metallb/speaker
      tag: v0.11.0
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
    prometheus:
      serviceMonitor:
        enabled: true
  configInline:
    address-pools:
    - name: k8s-ip-space
      protocol: layer2
      addresses:
      - 192.168.1.51-192.168.1.99