apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cheese
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-live
spec:
  rules:
  - host: stilton.cheese.apps.blah.cloud
    http:
      paths:
      - path: /
        backend:
          service:
            name: stilton
            port:
              name: http
        pathType: ImplementationSpecific
  - host: cheddar.cheese.apps.blah.cloud
    http:
      paths:
      - path: /
        backend:
          service:
            name: cheddar
            port:
              name: http
        pathType: ImplementationSpecific
  - host: wensleydale.cheese.apps.blah.cloud
    http:
      paths:
      - path: /
        backend:
          service:
            name: wensleydale
            port:
              name: http
        pathType: ImplementationSpecific
  tls:
  - secretName: cheese-host-cert
    hosts:
    - stilton.cheese.apps.blah.cloud
    - cheddar.cheese.apps.blah.cloud
    - wensleydale.cheese.apps.blah.cloud