apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBfymB57ufxsvEPRugFu4AtS3vfn4w1SVkovqYAcVe9yksoRn5G5tBCax2UNBbcJumEe5qyAy0jK1Wvs9eUeqiVZmyOOUI2TgB0dCygCdwFyEDWG/qBGMvA4aLLi9g2bcfla4NBnhDDkQbSkh8Xi3gaCqFRGecruvDkFdwSEMWo/0fXDPCsPuKTaowb2AWVRY3tT+aMOqI2eIEQQF7Z8m4wbuhFxfbmSW4hpgxfehi9TQh5+ZiCFkqNRUe9IAT6QyZI+iq1+hf03vbNZ+T6q0rVpQNdfLgyi/uLPQ+/m+Zh9GRzKA17FnLIArcCzWjJhJMTq0bhf5CxJWM2MaejgHnxtLI8TE1McuukYuLg45VNdTOm20jyPYL78bPMZIL4nU3MJ8Mj5nqr6SziXyqgr8zaeCiP1+ZWfFBq8Lyq03xyh5ue7sijPfH3375WoR6XvMNpvA3fCBzLCPTwi+qobGj+0ZJOF4Ol1IMGyIvqCFi1StRJEx1ltzsm6xCI8S730F2Nau3Zxuv2/ila8RBGsNfCA2M0gLLT1jrpx/HTIDuvl3i+IoD5PA4gZVztqOWdtS/TLiVibpfFvsSxiRYow2fBA9Je8R6hbXdJlXotYQfqDfWwpG2u8AYONNzbtRUED4LBAKxGeMRa8mdniN4dd9uh+PY7j8xMstMFog1aCXFLIwcnIEvgy2Wx5pgPNzBF50jIJ/KgfGRNgJMcHqZUEUJ9/FxwRnzSqFbviM8HBzXQChCGhCLjKU0x
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque

