apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-minio
  namespace: argocd
spec:
  encryptedData:
    accesskey: AgCiCMVFeYSDYcl6tOp12WU9MjrggdUftSu8mNS2aVN0GUBV6X751o/628lMvCOqUCPYler8+UQ/6GcLrDxRYDYj2YjaWY0qruRgWLAunCMQ/fZg03ZEbaOUgM+MbVYI4wMVJSPr9DnC9PZH6SzWtP5bvoD0AgG2u8OiTdy78Y5gGQkgi1dbLHCwMFLRnWjlxLCcGFwlpx1ALZnQN38eiF1AaLjYc8fqefPuIqs0MRHDH5deyHLxmn6302zrefDrdUqIPy1QyRlU2dO8mjlpcHDIuNqZJqCJCFKok+7gi0zFShei8bLq98KtegdmqanczJY8lC8vHATSIcJMmgLZLiFJp0iaZ/tvgCD37A038E8EV7AnJV4Xp3YPY4vkMhVwL87mlnjnDw5XKtviM2g2xmTmzHtsX9wsc0fzeWWFfWLpcTHskqZIDSrh/HF4DqC/t0nGHT6aHJc/7kUIpPuSXVh1SO8Ir/sPXUIalrCxHpeC4MlUoumgIcT4BmF/9UafW55lQeRfkvaFAFzn573kt8oCYVZbmNizh/LuJvMo9DlP7y/+bjm0K/oJzRTWcFjvwj6tDdhVMVPXmaCqKUEzEO0Cx5x0gkxD1SftXX2vQjWWN+wRVeD73UJjpL+ugYhKGBW+H29oE/pp0CuXGTiTx5hEt6R917FQCDWI6nwHAKVfcDHp1MjzDt7bgVsQAUyxTN7FsxMkrorfFFU8H8OPN2lTKsT80w==
    secretkey: AgBEjInHeHWJxZQFotnFCe3QRvSwt+XibFOHD3X29i0H1P54mPKPdUIsrlDgLF4nmaRTFoS4mbOh0FRaMiMLIrcluyNAlgBVIAuZmnAVCtXWhRd45wX1/+Q82sC3c1OfoDB0tj2k/5PWtTWLwD7R/YcyGuNAUS6uMRILS4tX2A0I7C4e3EXwxbUJLqDM0ijI8BUPYGf8a0hzoyBli1o141j2FPcNCKccuIV+jeUdUSTZGqp/urN1DWD2TwMDbn/bIeqi9OI3m6KOdEY2MPJABJOVbmuxPrN+BIZFY7klcSNcwXT5/df+5ODE0IS8ALg4f+acMJh9QYR07lahYHkldgXBOVYrI6F/KHb2eun0FRQFeifd2CYYyNMMfBiFnTmgFFcnlyZ+WVFq8Y2lAAU7uq4ANoJkzoNOGdYXEncPm8T+SHmLDa6Ig/8UyCVfSbXLinAyqO6eVolTnuVAxKk1bWlQ4ALyLbxIUIA3CuMIPgyo6akvdCsVTQR69KWzLCoUbD2to03h4nazZbLHK9mmcsr/kMMp/X3W6ielxDNP/APsUBxoDKz5KM1xgV/eDVNJ0H0IXo251OzuZQSHnSdd+DiiE0htH9P+NZL1onh4yoClOgh4H+51IWmFWxpqZ04SXN/aSzz6JyTsjQHwxQe57b80mdNXnfG12yxnjHRqKAzezU4ePNhTL5WP+4e/5W+R5O0gr8702bk5wFLQmXkefHC/437t7HleNkHVJ5CY62CnxS6Wu7+X6JDr
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app: minio
        argocd.argoproj.io/instance: argocd-workflows
      name: argo-workflows-minio
      namespace: argocd
    type: Opaque

