apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-minio
  namespace: minio
spec:
  encryptedData:
    accesskey: AgB6vUAoJYWyY/u3htL9Fs2maLA6cDK9cGqs8T3wrngGJqOOB1VXZeLH6fu9bO0DqMCtkeVsShZS4cvIMrIn6k0s0tVlB15Z6+taKYmv21GGG4pHnsgvzJ+mfBetDHsFijbiOjIE9Ssm7qtIV17z2bi3tYFWX0WfbB1sV7gxHqQLf9QjknHezt+Vudkl/WY2OZbDuGpPzB1eulEtdewWz+bPIp5nVS4soRELCcpO3Qqnwd4OGyfDyFX7Xoh9RIG4NbzX3anRvElUDqfcx6GW4a+i9Pet3ttRpSzctFkXNRVIRtD7fF/qw2S9vb3++LMfFzI9P+A9Pl38u2yLb8KP+1szmOx0aR9CpV/5b1IwNrhE5y13DKSW5BcJ10Pu0aDVsrRul4PF2g3l9fwtNGp5P9Q/Qq/lfLaddQUm5xzUTx+Exz3EmlKiU9wwZTC+VINlzmDVhbpZOLuHRfqU2ULxeD5mNNtUrLjai0K7qOkpbykfQ5x/7BqQ5B9oyZHHR/qmhaXDAZZinwEkh/jSlEyA7u1zBFCYvdvkEnyRjEvp/DNRhs+HTx4q89nyYogjPeDfaYrfRLJcnB7zlW1pKrUVBKX47n2vp0jOhNFCWwQsbzDw918y4PjYfV1aFj3Vnxtfy1xagSMXM2WQJRKLlTSsjNZhZJy9/rb4QXPEoWjjLjtZCpUdL0xUPztXdaKmyBJY8EmfzTwhGvYDYq9Z2VGEzghhOGsO2Q==
    secretkey: AgBCQkxbXtnu25/ZyzIPuBD1jkhlpuQ4A56MBffTWpKuwRqUctUGN5qLU7xvg7j2n0JnHL/N6AITVY3EOZpUcsg2hgw5PCzCM2shxChIYx/FQviUaok+PEM+OO/BYa7JAbVsnMFw4LnsxVktZHtUTmTC+PwJinW6WTuGQ3bqKvQgDRH0y+7DthLzRch+nUqeb9+WooUK+aV8to39bWuSyVMiof6pHi8R2qKay+vEW/yM3JGeSowBz2XUTdaGbI8+yeK4sX3JxAtdIW3qnI88gASavmQTndeEUKjbGjTEmZp+O6ew6vTLV+7uEO2pbW1uANvWG8A+E+q6JrLKC6fPYAOg6Wlt8Nm85IZ9FBV/lXxZQO/KvFqbr88miSQZG/QwTMNTDxODg9IRjxfedGVqFPy0VwXHSPlqKvrxf3Yfuxmg1N9cQyyLy1geencvWh+f4IQmRtC2ak9BqSPhevND1YTiyoPDRt2W9byRtIv5NiWss6hwBjalfBgEzwKV20CpBrl8zoGAuNwIc9hfC5wia/Ul1ugQs/negwu2qC6OxWbHTSoG1WDk9ix3lfmqA4GOzRHU5JFA8rhnEe66XMgR7FIm7KJBQRwDaI/3aaHvVRq+OfoOxTrmLe3yFUI0t688iQ5ohiWDELNZUSvII7gbWWDsLc6Stx8x9GlxIJ564Xd3yJGhXHS6GOg43IBIr7AP7KnLn96ONGp1P8ecKaITnetqnJXnie7EyMK1JpTeyYDQVrO/RwaADO6b
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app: minio
        argocd.argoproj.io/instance: argocd-workflows
      name: argo-workflows-minio
      namespace: minio
    type: Opaque

