apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-minio
  namespace: argocd
spec:
  encryptedData:
    accesskey: AgBu5/0J5o9hPrpKCFFAY68tnNnRZUX2oD92BoKMhIX72G+sz/1UeukEacUnSTvXwSm7r9vQIE7vCr4iBjNCECuLNpFn9WdCBFpfI69rTO7FGAC97nYqHGooaVd5Z2bJdC11QAhB23mf49LpLpqIwXl4BZdT32Hcwf2/j37mwE1BmfJlfxOnpbPg4oyL36n/eNNMpRubY+fu0sFADLmUbuo5yDlFaC3G1P6uKFfQ1R5fJj1W0YHQW4Qu2i7u61Eg3/SpVnb4+Di0Ey5fbc/ieHBK+530w6bT7bfZFSg4OTPJ9HZAiTRMp4pTnhM8lt0ahhXDzpujBfAZJWjJKihmH3P89ETYiRjL1s10ZnyKguPN10meHyE9C6lJh9XI3fA32qf4OcwVMageWd+QaDglc8Ke0A1UIIUdm6UwFbaGwts6icx0JNVhlmX5Aq3O4iNUgpbgMx5gCVuMKblOFfkdtlwdaSeGJV76yzLOXbj0q3lipKocIeSTH08NwTNqgq6HWP2Q4eGO60mKgyf2Jysr9gL9bDj1gLmMbqcON3rfKg8bbQSpCzwy8FE0X/9/Q4gkqWKf45J7+RUE8FJP/GF90/krHEX99Ez5XbSVVgrOWcK898oBKngJi1SMz9RjEbpRuWLhQgQ9h9W+hh9u4DsSRirvmonsb+AlIwfGus85xMQtcDaSERQjIciMY8gBX4CVTJKZBgA2EWdx0MiIVyWbFFrIgMmuGw==
    secretkey: AgB/+KdCRG0Z7AwvdbT/fA/WasyLrvMLqEq4SKUReBYw3Qmid4riYHEimz8TV+uUEMlIcCaJOAriVDH1x+9huy/SQYVrrT1QVPVGBFkCpCaRjH/+n3DwD9dpKwgxm3uDT2Zwpad/yjVOtZqVRhJcwr2+5iey4ktH8EtMPzLdOtyQF5wiQ8z4Iqvtuu6ITk9qBI23NItkzYtm7fFI8P1NkDSYgi8JOe9hZNOQbtxJUtZWfDCNsmHEyN7d+qJgfyUjpACFy8owZ59LT1hdpev2gJnS1NjOutq2L7y6CW9i3lui/8JBx62Q7kP+4z1Gq9vw59FvMmqnrOymy6ItF8SRqP76aTbk+mkDl0cxsoV9GNBdmlS++xO6jKqeu5iYzQ9M2h2Iz0q56WblIaIcSXYjmDVtUzHazIWIXD7+lSuLajd5aXqhnSPtGhcXumkV8XWGDs7rquOCyj89RTwEAa/jeklxOC/uTU7pg/qin7XNCPKHSckPEsrSGsrPf61ePbd215kESBp2xhSd/LZYoiNEgu6JbfVSp/zBBk3GkoBWFFo+HptExc2BQFRFw4FFSKqAxa+RpnnKrv2E52lCIzICNjXXztIGazSXHWmCLwhQFw1b9r4MCsa2iPjQ8mLAc3BVDf7wyQ8K5/8KKzBF+Lmvgxh49KyeXOi42lDuL5G/fmnS3AOqMeo6JFTrVP63ryHJvfJPOjDvVqc14w7AC7gFrUXTkGZ3CiDpdMiJXeYCejCGUMe4kpM8AmUm
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app: minio
        argocd.argoproj.io/instance: argocd-workflows
      name: argo-workflows-minio
      namespace: argocd
    type: Opaque

