cert-manager:
  namespace: cert-manager
  installCRDs: true
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
      interval: 30s
  extraArgs:
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=abby.ns.cloudflare.com:53,sid.ns.cloudflare.com:53