apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-dnsprovider-config
  namespace: ingress
spec:
  encryptedData:
    CF_API_EMAIL: AgAKsswQWcWHpIIo1G168pl9c0UBLtRQM76mbOyIcaZ8IzEvdqDK41CoBw71yDoQ3XzfWyIgRoEuv32NtNfLN4yC8HSK7lQOe/XlUjJWbisg7Kvo7aQ3fs10FDK+cBsoGylq8vOZVG2GF9qped7hzaQl7DqOMNTgjibSF6TkWLFQ4B/H/KiFtE8UCe2Vv6s1pylFek26wTmt92qA59mqxHdNCNb5vRD7k9chnuWkjvyprv3Q0cJECzGKhSlQR/ryW3B++o2Non2H84GymHQCrKiIlPjT5UE43qZaFnIhvgR06iKvNwMZT/xFBrgbrEk4Ce6If2lOd6v40aMpX0IraBVxh0C8BUg3GoWtoYGk9FJKpvHxT9+5E7eZNcH3ZzN6iLb2YDs4iO6GAN9zNY/o6/vv1Dzeda1Hx7B5eZ820yQT+ZcX7IR1IziwpAR2xkhuydTs29KCIE7LqQnbPm74O+U6MAj0fksczzNkOXaLHXsxKoxO45MXJTdd1yYNgQ4KRDMT/kCLVqKeR0Lu5tmK23G4YhLRl7SHoCQohFnWD6900Kpfo0bXbKeu7XKvqCm+GXW/4q7YBs3uPrjCh9CNvhEdNHkoU8aU37QD80RBRZQVBYdAJ34eqtp1CGxp7CADgLV6OdZ2IQPTaKLyqF9zzxTtWgMHk/g5gP0bknv9i5Wh51O6kEsYf60+Zw1ziuy9ZxJ/Vem2I4Wz17SEtP2WFxAH
    CF_API_KEY: AgA+lUD1VmkSY3dxOtVPswb6ll2nTQDHu/D1dJcp2wJdYdedPfARwa6fatX9/gMWye0HB0yTnbD81QRr3VudEWHvN8S3vaU1alWxMLSYOdq/zPa/MlKQHGRqIu/sC6bRVKITvJKlC5oj3q6CHkWuQa66vUSwHsC5Y290sDrs1Q8HLJFtEU8/rBcsaDvJ1dgEy+KTa99CYhUuKe2u8CGJImptVqEj34/2r+toHnViE51AaIuqloUkp0nld5bq6g066OaBbQO7YKSTJUL9kEE8BMFKevTrOp8SzcT7ZaBJ8JrN9LNWknhz2Pv/Bjotur4csiay/oATUsSJCpU7SkPrbYFXZivIjE58r81+pA+bTvi6DHZs2OXgXXqqBfZ3cnsO6TdQ4gX+vuOaLMsFLpVzOX5EquMPpmLyd9FWQjn7GL6smuz/gLGngRMyQnV2/GgVEPyWbqV/a9eeiinedqdB/7VTX2vvC/nri+0zp9lE518TJAwjURpc88pzA8KXS9USDwmD7oRCUYpR0G0ROEjSKXM2a6D17sfSYThufhSg1ZSTZcYJ/IwNu0vxFxUt2wk22QXnR3px4sxOKhuw54c3acLR5KcVwC+/0+q3nuTibughaP5dQIW2BWl+ltdQvrc2rJFx7H52YgyssodDAVDMdBl54M+r3E/Sjl6CB88hNml/PKJ6CetWKYApK7gCtml3Yy5vkc3RP9GOwlkxt9ltSWaAgRc9Oi++CsgYRW9EGsx5Hw7dNyhG
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: traefik-dnsprovider-config
      namespace: ingress
    type: Opaque

