apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-dnsprovider-config
  namespace: ingress
spec:
  encryptedData:
    CF_API_EMAIL: AgCQcUdNvtVKRYNx2uCmKaB2jIAe8dvA505HLgrc9F1azHcmqKlK5w9BIf2A1fEbHYusy5G+2Dw3dQ1r/uHZfMwuFCL1IRhjKpzd3GvZ3jhSdekBbcYmVxuZiMvvCxI/rC2TUHK8OQTsf7TSJsfGgoMUviYKJSOoR/wWbGq6Z2ncLvwbTwDi3eYYki/oIgEATR39nlLS5qdbJxKYSBamHLN8jNPD7/wmIhCs78TaCBZFBKN7WUjBkgl1H626Trz6uDlZxLAYlRPrFfmaIk1iIJlF9q/CQ3Qk1jrjZUIhxW7wGtrMzyPuV5VVYC20IpJ7L1q33CEfOAn8wIfvSXKfdPt+45l+A9nunlzaMiFKVmP0HepGKe2UCDJEC9n1lLjVJCSMxjEKQsTiVeCfC6ehz7E7NbFvllfuCbhVLErHDl11mVju33+zwQsI5ViUcAzM/b8kLxFzq7Y6Kc4IqGgnl5khhtlpVbOV50YaE4KrmneR5sWSbOPq/lUmJKUXoAdCyAo8VA3TPge5iY6xmwuVQpTjqSZxzcH8V/PB11m04t3kAjuxr4ObdasKJl1HEU6XsRXxfK63rh96s5zpqn4yX5t3eILs4HP9VsX3j9aHjWJP5oVq07w9mAQX1uvEuSB6nfqOLR8iw/hqpFyf2c8pYnuFfGGQJTQiMPS4dWw1UrHSNVNoENj3CyZ+XKlf0HztBwWWH0rXngNhec5Z+uP96252
    CF_API_KEY: AgATalCWu5H6BVjlUBoCVNyXLCKSx/3hruCTs3lkSQSWpz1djB33DtJLz5aFIl9Sozdzj/83G3Ps5qc6p9fgzV3oCaVy37w/S2D/pPjuejqobfDlwUpuN/8vK36DPTpb5LFYNmjQJ/fYJGZDuEDWH0V3u2nszirUrQ0ILBGhwBGyxD2QI6j+DuKWt+Qw0geBJKRWAfSkDl7Mi0A65rbkLPXKZ8+C08w0vGzbqqsdWqWz9PbojQ3jg8ekc+10jWPS0efxtIMBjVNjBTp1DuYNxROj/jMLJgrKHRgseWEA/YknRy9wz64ZkmsyvNY9wCSEU0w2AwxNX3pqVhPn2/MxeBnrmLC2sTD+qaInfvVQKSWnBLrWwR77IL76FP0JAdekSfGuyaLaIgiIkR6tDaRNa/OR6TaOUjbpaj28veZ6483ZK/b3c7uiRECSemX8K8g9X0W9cGZmFc3atNDgFZAvA7h1+qdOXNAp7AdGDlqS5txF6gnjijDJKZX9evTO7lzoOdAbhA9OGAUgStKkWW+4sDfUiLtlkJCmfjmMVSYXjhj1EXTH0NRix4Rv6rxDw2GPDDFyM78SAVmLVF1fZgRBN8QYf+pWbIb4fc4GQYjvVLYGVhopOZRvA+5dy/SP4GDMxb7zG34jUqQteK2k21i2VmFU6JYG1Zldu7RaSYfh8TuDyXwHx153jc518GO762wEWU3ZWZN3UqDYz+jyhbO7RIgcJVzZ1PMts2PrGboq6JyQyXepJNed
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: traefik-dnsprovider-config
      namespace: ingress
    type: Opaque

