apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-dnsprovider-config
  namespace: ingress
spec:
  encryptedData:
    CF_API_EMAIL: AgAv+niN/bsljx2NsoYd5zJdnvj9ZMdnFagAHB2HZnmVBh3fspSFUlDlEKQ0ZwR/N2fFqBpLnLcxyA+Sf6lEcOivfGcYTgEt7H6vjLbZD05/gC3BQREHUIJqDXrwBHZJNj9VMd7Q5wmZhsYcNjCPX0BER7zWKmbq7XUzD2boz120wUDom/cv0R4fLOTSBAy0HEzv9TX/LzoCO3Wq+CsYMMoKZYMxJUU4E2EzA3CBmvof6/zr4NoftYmLfNnb0vAfyW7kvS3xMNoj4JNubYO7TfP+Tz0QJZ4NFFo8U8kvni751J7rIaOj9vkB8zz4PN5nqazTsbhuffVPZWfG2fmdG7lremNGfymGDi7XO660/MO3jVvXYVvD3V7QOTjKoz98t12x8Ozgmb02CzQWQvEU1QeqHUjq8Dx12m8n40s8OTKkmr9ahCpfTeOMf3BAqkoJ7mlDxHprYCAAQs1Lf18m3SSR1I7UU0gMvZDcL09SolxRCpLrp0UXkz2KLzAc4HfuUpQJ1SzmVC4pEkB3bWBVA44DwMmJzEyEqIPOXQLh9gc5EiZf3718y6Iu634av5BU1AXppkOwx+YJVOVsAzLdAnAAkJfuXpKlrLiG6J26bOyKrJ00AUeaqMOqgGsNSOSwMWO0FF+JTgRVeRn0pMBRawffuCUyTIqYFu6L8K8PKac7OerZWoVvM1IDkGz8HaqShluTgre/ROAXV8jsqdC4iARh
    CF_API_KEY: AgAqFWBz0f/XOfBk157mKx3OsCupMTEXXgVDbvOs9aUufw9O70ovB0O2Prc1cJoxx4IolZTP45kUkapZxfzfcLOLUKf3YjvOXJBuDWUuNznAf+Qnn08OZNDpJcWP4ViCTtCRvlpYY+qJONzdfJE5iXsYmc2ZUUEdKCJmyGH6zdrUiSaILg5GlCL0Oldf1473h13gxvlFCoNMK3bRTwTH/BPT04I318XELk1OFYP+M7FQ7Q0f72V/G3CCbvugdgD2jFcZmXxzpSl1M5Mlbwc/YsG0vqAjidvoE4a/LBDkcf5Z51CTQBuaczS6C/OVSmMT+5ybb6ssICeikh6nUiNKrIarQIGJ3ToFnrYDc2ApGGHJL8lSaZ/SnApegcCESXGw5uHg8BsjzwagJLzPBizghX9UlAzRv20devdOsSkggn9PE9W7U9XyWLiife9Lr3hda2ptn3h9pWR7rNNTTzVA5ysFysPSVF3rMdOSBhAiRO7pWBkPsCbiQNs7FK2ScdRqW0Y63/Ox0slMSj6cUch0odo6bGUgYLIisbAoremPbdNCsPXEEal3Aggw2ZWcl5WquvyCEw3O8wHANpDU0XvNFoh/iiXMoCNF0hobH+i14FlzCcAY3eDwcz7ehgZX7/zcUkDaRSOoBmTAvySO0n1wbemkpd67b1bPcPlRT3/zwd1zB31a77H8+Pujla8qgDD3392Lxsg+9EqQTb0BaN7Iq9fIiNpwwZWhzN5PF7PxLdIP1sxz6EcZ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: traefik-dnsprovider-config
      namespace: ingress
    type: Opaque

