apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-dnsprovider-config
  namespace: ingress
spec:
  encryptedData:
    CF_API_EMAIL: AgARQDKjVvSRVxVbQoaym4S3ONonyTSrJvxr+vtPN9UjJ4cxMXxTkAMqR9584dDVzlfboaugzWJ/7utw3CADz4n8j5q0GjOGcdbHv0SYxmEdNf9jtD5m4alfpsRGbCbBhwgLI5f7LIppXKtFlv8ucuODCKNb7SfY/YYGny3Ic7vbwyZFXxjbD6yyONO33dXQok14tMUT+lSGBInsZXtvXOAsUdcuDQPtkUIeHwR/PWRIzSJbi54Al8lEIviB5IYBpY6emKmQP8WSim07vjrzfhvD6P8yD3foQ+78bIlUn6Gjo9bK4nbc3NQoVCnAzQ2UuOb5KskL7TI9R8StNtq9WwE54YGTQ3EhfvfGmlFQ6PFJ/6er8pLDjGS4VE3cVV/awsn0ZbE87yKFzWbSl9wL4XYdUW9/hsRwdkgnKeMfMJJh0iVKOrJpY0wDRblKc6gQu1cl6xNx3PEis6T0jBJlIfRpLN5pZmn+igVnHbWTrpCyWQI+1YntjEj8x8AsjCm0UaTouFfrA1U2HDcrcc4260YOdCJq8/CauLflJWFJXBO5bCaMo+oV5pWmiPoE/vTPNRr7dr3U1QbzO8/YF4LZ0dScLuu5OD4/BsXXkGWid0QpxkWxEcXzw6jPwt366yjyURYd0oPhFjtlN2RjrgPvsfLICHmjGZfmyBHCGRBxhU4EKHTOHC2As51pNBUPCvgeI7HlZRUfUbfqZW6s7rBFcVcF
    CF_API_KEY: AgBjoF1EaFz5VG2B56MtQNlKgfN7cp8CklZs5Ff3tqhditEdZjqypMSJxLI2LOHzYvCUBMt0LeIDu5+kc3bAhRfnljYNgcYNb/Cl3WoMIKtFHV4lhFx781VMA0ux0amPD3A+vWd0qe4yECiJbmMUfKrjeQm+tNepHMANsXM9fRiay1kATP6Fr2UEKLhrfVxfAC7S1VL8VssdqutL73Sw+6CX5NgRuv9b4JFNc5rzSqLPdDM1z9v4Al8kF+/v0gXlrCAaapwmxW1CAlTBX3rqQtI1ug+3cBIeusAwQ2Mshaj+iSKusHz6q9frhq6D4sDHTxg4KaFFkOXd2WAKgyhS6P/K2wAiXzYpviX8I0kzlAM7x8+T/e4vjoRyNy2DG8kUKG4/p9Eofcd1yIyLZUvRkWfpAD/GzLlB4/ym/DNZetJEGdn7WCj7w7noArXJ/Dk4x6Z7mDQID4N66SFv5Z+pArvT66hegaU0DO0oK90XUrJ9tUNLX+XRPVmYG92AaHZYHF2UAAKNDx6Q82yvlE6UmJqdeRpsrrgo/ZGYCkhhVaDKd/StjJcKV+pg409xbQ5k7gy3/8vsRQOy3QzxsY5fTMLymRwN9+HnHI2VpGMSjP5RdysJRB6cBJNZmusRdX/aHFum2zsbBFGueg3BeQyQF59Cxu3zYzMiho8QnfriQ0AL7N8umMrFrRWN/WdVk+oMF6I6D+0+C3aBOfQTmwpmU/LIz9D3BSc+aCzJkzs212KveXfy9FB9
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: traefik-dnsprovider-config
      namespace: ingress
    type: Opaque

