apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-dnsprovider-config
  namespace: ingress
spec:
  encryptedData:
    CF_API_EMAIL: AgB2c0+ew9e37oXcRXkgGUGxTQtyuJzmm0cVBu/ijGkPWY2T8I7nvvZlPiBnhCOqpsttOKw1ClTKkeF9hNgaFFMo43k4Mu328KXShB5RgbPElwcUfxnOqAe4J2MXeXoIbIeq7oLhPth473EV7HcXkJ0RBdWhXXQ2zK/R/mFF5sXrnuxmowaF1O5ttjifDFjhr0k8h4sN+SMEAJdpK97USNQ/1+ED2JaFtJk8GOcHZSX19ozirComBjghgpQfiVBEh/wKbqCpcCRmmDMvUDH6wpH0E7ndTcFC+Da3/PUsze0I7871jdp+TB9pavRzQEGD2PRQej2FFz6Jo+Kij7JVRwCiuMDl9QkcYM0k1J8aw48qTgaxfU4dQ4EZQ5zGO8V7cinQ7DoaV4SQuJ/m/g7gyNuYR0kylrCMxHvRiNMwtD8qt6uREjb5O1pUXZLaB334rrinSV4Y2KZynUVTcEahIQ+nRIbemI1BRKR2vP65FkajwSytaJ8EcywYsIQ3YXWQFSup835DcW9gfU+n7XXyOM3nt87qMnBNxFydZD5zLRKX6l/C1n+ApNiXNAcPbfMgHwVvajDlN+FsLClHSXsJuu8Z0egklCUVJ11IVHb1IKCSfp2SM7vKGYMsQO/1bOTFXx3ynYP4d6O9BGX4mD79dA5JdIvvOL7iA6M4jZDxNtId3VNweFZpJXBbmkQVUnRtwaO5EODVpKXxAgGl/JMHhDCa
    CF_API_KEY: AgCGYmcZ+eI0hCNoSUFiToB/z4ghQ7Wg9j71GNYZTBP9u+csKTlU+3MON+iKw+JEkKahw+X7GxaW1b3yOZA8FZi4/0w3xzIQ+1epfqERvR+xl2HaR7UJtEn2kC0tSZlqiSNfs/F/3Kt1kaBfA0N+CTzbL8X+PGnciSPyHbklcLjhZKjHNp9Urmt3BtswjyK5+8IRpM6skUH5TWH6iAkvdUb+fUlWNu3AI/7w1NxIFingpoKwBkNcV/VzllkaaVgwUSObUF2feMWAqi789664rdMrVotXiHEgg3RNyfbVZD5m+huzJSRU6/wBgf5Hw9UyHZRLO81x92f2P5jZy2o5SF1CaREfC4NUoSSSFuoIDsQPVZ5PnYhA9wnPS7YANVk/6VQpKio5MCBkw/0MxZLzMei3XyswkL+LtaVM8zCkxtq0OFLKXZHK5/rmhwWjk8mHvFNAGnt9hqACThNM+E2Zs28rpgwWOTA8hyVteYbARlLXsRxETL2z/NSW7F/RRCNw21V6YQP1xapsVKc5/ZBpi52zRzhGGBmxnb2AnP2zhCsvoq6xS2JK7emdZff9NNevmFfqnpzgRspbcuSMI/t2GyiPJbmwvs7aB4/7j+//d3hRRabaJclaFMZ9Y4htoOxHYn+FqTWTNKBstD+n53rCuIADl7fH4VNJg6kPul6za6UB02RVlYwFO6D8u73V1opMG4Urmepwe9OTwvdNsdIcwDqNv0/oteMsSg0S+92zQ/FZkFiKW68i
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: traefik-dnsprovider-config
      namespace: ingress
    type: Opaque

