argo-workflows:
  workflow:
    serviceAccount:
      create: true
    rbac:
      create: true
  controller:
    metricsConfig:
      enabled: true
    telemetryConfig:
      enabled: true
    serviceMonitor:
      enabled: true
  server:
    ingress:
      enabled: true
      hosts:
        - argo-workflows.apps.blah.cloud
      ingressClassName: "traefik"
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-live
      tls:
      - secretName: argo-workflows-cert
        hosts:
          - argo-workflows.apps.blah.cloud
    extraArgs:
      - --auth-mode=sso
      - --insecure-skip-tls-verify
    sso:
      issuer: https://argocd.apps.blah.cloud/api/dex
      clientId:
        name: argo-workflows-sso
        key: client-id
      clientSecret:
        name: argo-workflows-sso
        key: client-secret
      redirectUrl: https://argo-workflows.apps.blah.cloud/oauth2/callback
  useDefaultArtifactRepo: true
  artifactRepository:
    archiveLogs: true
    s3:
      accessKeySecret:
        name: argo-workflows-minio
      secretKeySecret:
        name: argo-workflows-minio
      insecure: true
      bucket: argo-workflows
      endpoint: s3.apps.blah.cloud