traefik:
  deployment:
    replicas: 4
  podDisruptionBudget:
    enabled: true
    minAvailable: 2
  ingressClass:
    enabled: true
    isDefaultClass: true
    fallbackApiVersion: "v1"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - traefik
        topologyKey: "kubernetes.io/hostname"
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  ingressRoute:
    dashboard:
      enabled: true
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-live
        kubernetes.io/ingress.class: traefik
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  additionalArguments:
    - --serversTransport.insecureSkipVerify=true
  pilot:
    enabled: true
    token: "3226b582-d09d-44ef-b0a9-c1ed2432b9b3"
    dashboard: true
  # experimental:
  #   kubernetesGateway:
  #     enabled: true
  ports:
    web:
      redirectTo: websecure
    websecure:
      tls:
        enabled: true
    metrics:
      expose: true
  tlsOptions:
    default:
      minVersion: VersionTLS12
      preferServerCipherSuites: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305