apiVersion: v1
kind: Pod
metadata:
  name: tf
spec:
  containers:
    - name: nvidia
      image: nvcr.io/nvidia/l4t-tensorflow:r32.6.1-tf2.5-py3
      command: [ "sleep" ]
      args: [ "1d" ]
  nodeSelector:
    beta.devicetree.org/nvidia-jetson-nano: '1'