apiVersion: apps/v1
kind: Deployment
metadata:
  name:  jetson-ml
  labels:
    app: jetson-ml
spec:
  selector:
    matchLabels:
      app: jetson-ml
  replicas: 1
  template:
    metadata:
      labels:
        app: jetson-ml
    spec:
      containers:
        - name: jetson-ml
          image: nvcr.io/nvidia/l4t-ml:r32.6.1-py3
          livenessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 20
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 20
          ports:
          - containerPort:  8888
            name:  http
      nodeSelector:
        beta.devicetree.org/nvidia-jetson-nano: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: jetson-ml
spec:
  selector:
    app: jetson-ml
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-live
  name: jupyter-lab
spec:
  ingressClassName: traefik
  rules:
  - host: ml.apps.blah.cloud
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: jetson-ml
            port:
              number: 8888
  tls:
  - hosts:
    - ml.apps.blah.cloud
    secretName: ml-jupyterlab-cert