apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    run: quake
  name: quake
  namespace: quake
spec:
  endpoints:
  - path: /metrics
    port: client
  namespaceSelector:
    matchNames:
    - quake
  selector:
    matchLabels:
      run: quake
