apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: keycloak
data:
  development.json: |
    {
      "enabled": true,
      "realm": "development",
      "displayName": "Development",
      "clients": [
        {
          "clientId": "grafana.apps.blah.cloud",
          "name": "client-to-be-deleted",
          "description": "Client which has to be removed after first config changes",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "my-special-client-secret",
          "redirectUris": [
            "*"
          ],
          "webOrigins": [
            "*"
          ]
        }
      ],
      "attributes": {
        "custom": "test-step00"
      }
    }