apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgB4Av6+gR8n7Fqofuok1T8qwkNOIBjD+g6YWopE4oEitZmIorJGaZa/YkZG/JGiqaGgXPQW1XHS/39hOKqrtRA3RTtVkhXXpxYIPQXyw7nm8hLvnPxxJOamQLmnMHNYqn14i728ggIeS2nIm7QDD5bxhjmRyOjEHvFN+PqVza15CJZyMU6v7AK3NN0m7gFLiV74F9A1MH/AmjSQ26D60VbjCDb7B5Bf2MP9UwqGSCc8xheltrTTUBbCw8cq7bm304SEI+UPw7EugaoS+mN9TT6iuIIumUOWhhz+OW6TCd/fslLEM4IJBG9/qZvHX5Y+Ma4sYRmlGmDOqoPFveix6Pf/zyHw4lUTPhqSCWjt63IIxWnPYjvPw2rOiI5adccqFOJ9BP8ajmL3QVdhII+DCVCzNWd2RkCl9QEGowW2vLl/KyYeg96noMIvCYvtZQLzPi26N+MUd/nQ9PitVWZc2gK0FM671HbTDcULjUb7Klh7uh63QUl5BXacYz5OmraO1DAuUmUl6igdMoITyFD7EpREEFWsWcSBTJQyL6XaIjgV4HcY1+19nHjiU51faetmEFbgqRJ48TiXqHmqOql6U7DjBu/iMp9AZoEcpp3ex9UIuvAwMZxFPDnxD9gPepiHmO8cx8LS8W5NTVt0lLLKe2uIrzXzs94LaYe5LgyTLaHU1j/jjtm1YCN+e0wi2AJSX7+zu38Wf9pawee3qASC
    postgresql-postgres-password: AgBoEB9bpnNLvIQsGLpSWsGDjzrizdMB5xOZkHvPdaeP+hP7bIUf573IZWa5ltlQ0T210sjXz1Kxv11w3d447Hud96/uAkKwx7ZZ9PqbNWuOw6CwGA6/O77I9WBpv6+ExwSvkjjjkynMNxCcUfEKfEydaHX3A/n/2aUhZvnuZafOHsuSKD0ipJbenaoHP6OTPD2NRMaQssNJ54ni4RUxJUG8qlonmkUioST0vijEslVdugNlGv/Q/HzIUH5ei4jQSPt59cyiMuwPvC4GugI3wIB08fxfWE6VFxgvh1Y/9wCDhnn701ndyV67x/ZmeiT0Psr5DvYcrTkQggurv8xghZdeooA5oAdUsdX3ro3Iiv6xvaaGNhxsI99M+rN/AZeY95gsJvQguLAAtApoXRtUSzuORpPZ2H2rd8WPHINJH44fELrJBTajr1x0kQgfI+tDYbM+rIekthkm5zg4wI4nP06miXj6pwMfcGqwkyepL9jZbGcMn3vbCb+M4h/fwSn0z9N8pFLnH2/qCLARPQT2SGD6k16deXnTyrsr13xTXc8uXKT3EulS7b0YYOe3dtmyo/pkFghLd0v5T0cCIdE0Lod87T+4I3PI5FN50Tj3b16J1psD8MR+20fQtHrMvOMoPjWlRnDyz2ae6YBxJXqzlXfSCWKZg7x2HFobT7AbSCg53EkvRCOIbWi8CRfAKv12g+d7v0aHuDex+Ryq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

