apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgChhFScy99qJJVa/s/W8nR/YXUFZDNW0ByWmLn8lIcKHsA+vBUOGIWBmldIxMpKk00bC5hnRyQkXO04f4fofZuRBy6J/QNYLimx6Rk8WBDCr9srw0yzITezncUK5S+YjCC4eePQxCiYuOrtfVEvfS10l6nwR40wBy63MXpW4+JfPE00R1WP7dIr6ERYdgl6h7BpkIJcU38NSKY+Ozjq9a+6S6ZGytcaZsWAqKF5IRBX00sAo+tUDEPUfkPmULzTq2CvUeL3Wq2iKXmWKK7e6p6yfUcEeng0OTqR3GQprhQ3bvBhKIk2JDIJ2td2aF4ulePcsGIxeDqsCia+ToNjVxtA16tFxA2MYmM2yBcFSpUH6AB6x9OCIKxtdQnhqyNtpsx7H9sGT/GlSTQ2idVQx21Jx3eZNaf/fMV0rD5XL7nAhvkAq22oFSM0VKdIr31i34xudc5d0BCd5+4sU2tSXM/OKd/yjYA2t0zFIP0i5kMmGrLUzVxI8EjpEZf5VXV8xGC7r1PyXIwZ/SmckAisrStY8RUWMI4XKa0fyGMbbhzVdmhVOnp3SzS0GASbMmObnCDGxuuf3TX8V6p7MUuICNJM8Hvzh9YdfvJcrONme3oXP6ggwuU1NPF2326W2dJN5QfpszeuOvJAeRHDuELsMp1myDHdA9AZPczV2zsOXXRUG0gK9H8f4U+9usAJKf3nuic4A8AhZKODaqd+Xv/P
    postgresql-postgres-password: AgB2kxWZznfLqhqG2uOl3h5w/APCugFKf1MJrSykrqWNZHsNdYcBX4hHcQMKk4Im2nrdUuu+bcxIiSE631wY6FCHERTd9MZLz+aeZ8sLoW/j8ceJM7+hU+7Mo0mkOXiC2xWbukTt5LpMv5cNcXDppXkBZLNQDxTycvxjFYLgtO2rfA2Okg0RPFxkXtE8kzeanDFTsJ/mDCgtapJb+fUICgej5uz6sQzjETHVEPlif1IjwqQ0eumKiXAOmT0gLqm1oLi5G6b+4yK3QTda+pnVhOqWZv5JKiowvY8koIQLpLZK0Vu+H6QIjo3Z4oQYWq/p/3/DldQTCyvEiXMZJqBYZRmLw86gmFPpbgyNztUH32RyDbg6sl3uyU9/5bTz0CG8EZ95HhTh/Lgmimw59HE0xuntcrbw6mP4z4IcdknlwnztDlzuf2a5cy61NtmrIZq54OxS4yN1uw5Dz5PHlekFTqvuGzeK+e4EYo3kFTuprhSszQtdv03GSIpOFtewtZGshIb5bGbSS6k6e7gRh6oGTlXmSC8n2KDeA4jYiUVVuoNU4IX5zN9I2/A9GQppFzKmbnJUn+1GFNZ7rmXizugQYowRvE9fTKJ1023gq6LX5tRAqor7AKDNZYkPapRM0eSGD+3qGyJPsbOBvu5gCBx7xlk3494vKyujb+/PCqIXlr1RfD5BJFk/MjJnG0WGgMt8648t+DzRqHAcwBdm
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

