apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgAIBN4No6jDuTxO6AhgtMOoS25JgJ94x0VJRRWNaGST4pXPece6T5dHLx9zUQYpqdTHfmegyWRoWXbl88kH/Ozn0wXib8j3uQOynYfwAr4NclKBfhhWRDc45Be2PnbX/QJRqPlFa1yZEmmIiYB0s8pz2gr9zWIJbNwTqw4YyhEZfbp8wLgRYtp6HgORgKiTB8c6La8M3T3XPlpYN7gVqvqVzIdCtLLqIa2lGMoR62lIHkemmgTsNtmWDfNs8fF2mHrP0HV5v+lJ603kMfCYNngeIYtMeczIHW9YP8VjIiI+fFPFn69bvCWzAmenWuwcz1BaapzH0cLM9mMxCkEkpqJY5cq1NWTGUJL/ZMyoXgN34sCQmEzrbJ1c15xa47yaKA90HnzGVfRGWTYN31g/PkRroRGotmc4qewtLoSuRd+hcwO8ecsq07abT7C+St4zAG7yT1fD9X+rqOxcJCt/XS7H1BfIn4iwcu/txK5tVCQjJHmlJSlSfpDpFLKU1j/pDYu7QxULIRd+k56urZv6AWlzOvRQCq3RmDNBL8tMKNrxyj5mjCgJfW76AJl1v29ZEjb7u12PwVOnafs2G3xBSGd9WtGO5qv7aEjtrUvY92OR1Exr1MLN2E4xAdbGhvavuNyQgjKvKcjNvGrQsHxRXndlCYVcxhyCa1m3xEtHY/993dVIUwJmpRcBwBPMMpmm2BRK2nMphopACJPtXVWK
    postgresql-postgres-password: AgA/z3yYTlSanrG4+kJUG4BQGJSmlFdwX+KeXyfYLE5N6ZtTHp9s/S5OWSETrpnVMuoQcHgDPqC7NDm2mKpiFYpKktbaP7Sm07RyDyMzFFt7TpRZxL268tuLGOCbFwzoqze0+7XEC7ThYAtfKYPBWTb/weQZx6Dvrj2E9K7hXI+OjvuVmpoAnfv9tGbiQzQ19mYihCMTkuJi3HbmXBGNVeRqcBV8uQ8nyHnHRkE8CTy2A5JUGbUJRCssvyLgXIgDTs2PvIlXHoWDhsf64rB+bhqpjasrZ6V4M1UM0jLdCJWu2KF5KinVLSgAwXESYqgcR15YXhIKJfaMRZ97DdHM3WJ4ZsGMAAwdUwTZFQqJ3404QeEVPWj8URprlCLq4+X94qnEw4zZ+3NMJHsB4TfGPvs81i3gacAtaK0oXQxYXMQx4NQ3d7q/5lo5TmgdHlssP5SF5rWqgAWqVNwHu4ZHtJNGdtrb3DVwWBY9qMB7nhYZAU/bQ6uAPzsxZr6d6I3N9FUO2mJ46D1jNgNHrhEbHoWisaHAGVuFvB9JZIL66j0bbbq3X/6y8dFyRoEeFRsrHc3no1+eDKiBR4sTz6tmTem3U/mdhEHQrlo1HB6977BdQYcVk1EaFvrOgljm0FzsayeDe5vzvdEwGVWOzNqDvjk4oT5cDMrtGs0BT3K9WiBKVYQmrQK/20hCsQFtGKJF8kn/28RIx0doZTmy
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

