apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgBucm1h54Ki0O83bR4FOsm/gJhYeBeEJdXCaLlic/loBPTTl2yduZET3PW4XbpFVU0licPDDZMnNm3WE5NKLiyJBGfR6EzH+HIgFHCjG/Pw4FxPf1iEhg0H0wBmD+tYsQ+aqq+mmVGf6WUyDpoh60tLl0qi0sTA+gZ0uCI6GlFNk3GaMqLV0vbAx/TJ6invUE4PWPrG7jEysypoSIcZxgHY3XvaL0El2auQtVPaFslJw2PwSTK+zLRi5u6kRXqrIIlTQjSAAc3MyuQJhky4qyKLe8ceSaGCuEXB0MrqAj12LjO3NjZ9AdxLkDmKQtjukFah88r4fZIced3FMQG3Zy1N0yfniOHZWXY+xi3PXrgoU/RBgB9MVLY2Sa98qgvp6SNMK6rHXEDa2uq5tAghmJqlX2aXSIkg6934MBJwUKlJxP2XmRzTS8l0pjK27/1IZC6sl21YG8BeT0uvfOU75LR/GSyYA64Xt5TBxkQ1iHbZlq2o24ZvHz/s1u/ewk0SSJBSj+70YY1yYvDucXYhL6WKG4hGNA/h0ywZuT68j4zMj5F5JeQrsyNV42f/ScNgMJI34vdsufTqPp2vdoVwgBm1Ktc44gV4/K95i0nBFCUS6o5KacoM3iWrZU/cXnDGsbq8aYAbnjTBEmFgbR98Akt1Smxz8dEpHb/YplXS/YCeLt4Uv1YWMkjqBAMPZAXuoQoHX+lJzz4u80buxWCM
    postgresql-postgres-password: AgBi/5p38GGkVH/+EZqLMnc9sLw659SLDvaVcTaA3ZP92AP9JPSt9ouBGsXQEbexXvEiA8XWje/8uzmSlIWyIJM99yMw+kqwQQDQBj69zx9fSll8a7FGWVFy61UjMOCC1jgfQu4BGnAfAE/EkzYBMbVYXhD665RqB5kuqSRPu8LybEfk/TY8J26q+FePPSmC/6lV5gYzSqAG9kit5ajPVnd2b5aLoHkx8H/bZ1ePyGVaY7TBXHq0eAJ+vqDHghgw6dt6d02cqnYF1if9XsVCox7zgW/uU/Dur+Qp3XqhcSSC+VLndgxd/hfr4YjYEOXZy+2c3mLCQsD1F9denn0x+WSxWqWLp9O4dkxCG7QP3xQdcSHPr7qEBJpq/gGhzNKezMV/z+nt1yKS4YUb5j66dCiBa5ticO3Cx5Tj8Nmjx+RqyqI3jUPlwXGZzQ1n9n3u/bJK16sD65aIHIXeAdb8srL+PtQwNGdVKKH+UYJlwW/rCmvK127rLDtEnHY/BXz+ClqOSzszu5dtg1bNmgoITsgpK8SqV+Xp59T/EMLof0T+TFzlS2qWJczptqNPWawKXVOz82Vk8T3fPlseO/AWAf5gjqxgozMsn58YaW1kgTognodCVufSxJRhVLprG/NmwFgua0oBz5kkjhOTzjoeACAreMlnU6WFQi5VociOCs43UwbbKviWOfef0vNF/RQUHFIqtxDDT7eToj3f
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

