apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgB6UW41ICCCcMD0Bc5a1Hau6T9WCjQqaawNIGCZ+cszTvn2yxScKEZ9EOWRhvgobEizHqp4wIXW8u7MTn1zG+m/Bk20nM2PePxAfT9nXcQcWtpx1rE42yjxEJHFsYPcACun/EH9C1eShZ7fgK4qmOnqvscpG+g8agiWmrg2EuLc53PRX9sFCAMFYba0CZdhdzcv3KmTBlagI+t29IiP23P1dghspvBHrU8cEMAX6RqjxNjUi7VmtKbW/nn0/wlsj85zml5BY/lyYf2d7E/CEe5IwDIswDKDWrz4GnSA9Ydf3asVNc3qRmE4HmzdH1bqPwNGlio5Hg/yq5bK+eeqGNhhGVi2RTtE0Es0gj6APKoxRdC2BbZm+w+qYP63sGLBPspaRIyWUNi6zDKpCoPNzo+TqNpmHfnp574N2Ey06IQbXVA+z3+7JKgmg0mW68o6/PqYgSwiZKeLOps0Jkoai/0ITMxZXp8Ne6BYYltUBLpQtUvUXmOcdm6OAhDVaA1kjHt3LOJ10OiUXkcjOJTUbEGLBr6F/4UjkBCWtnPEy2E/qV8kOWjBbKmUJUKJm0z2JEneVQFDIppB7NtXKybBDfocSfPDFoqQ07Is6EaWUdsB4KuSImZf6yHqX3Dkb7+5dLvJAzPGY6ltyYXoLegRDYVLBbQMfA2Tep7oGaNu/60dzn8OR0boa0O6DovNOgsa2B770nyl8jhxCoBdAish
    postgresql-postgres-password: AgCmG+kJ3105Xk9WUgG1U/y57wTIzFhJ73N6Yg9/mNaA4nUQKI8SAuX4W7qTCiUCN+b21b818Q+1JVpa2uzuPolssHIf86gdow8i3RWRbhAcQoikKG1H/hB8/bPfkhAV32duGJNTaoSU019d31QrnI7LMeW2hFMD096RvVl0lOrmov93gSphEVxuAG3GHS78sFdd6foFReTauhlS63zLYvC9EMZUYTS1/AIlnu5sAbCXyz5EV+wu4b1Yo/wOzQxz1DtEEOqlKuHu2RTIrl3SoNONtUGMMNgHK0ha11l3Mo0BrEyCYTA7+fmxSVkgryslWsQFIFyUIut8C/Fm7gG93KU1gzJbeCMHVshhKYi3+77/DXI2dB0muJ4/80SGm3ULDFN8SWcJtYHTIcP31Il4R8pHIgQvqX5+A55hXMY1DejNeH/KYuOw7N+Kbvo09MkfH9cVXNNYMgmhY3/fU38wlMVJtOdRagu+zSHTS9G1JpsOGQyo9/SoVqS40e8Q8MjBqBDl8Iqv6T3hpKSxJie3QEE6uDdGzYlPTSvNIh3ybzl5RHlVTdY+x+9UgRXxklThRsHO5uma4ZFqITjqrxepsDI2+JFydtbDV8Z4GF3S0UKJcdZIZ1wTQwvvV+oa/o7xd8nMChZ2GEEno9403zmTDMTZ08hnjhMtDpeYgHiuvs9hnj5ze+90fsBZkku66i3gZHvwUK7eYntl1ZlC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

