apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgCfQjn6kVLjV2/Wvcq7uE2dwohE94P8dz9TLRlBy4FcTM27LW9PjzWuHK4do0/guLg3cAIo51nzotDGxlOF5979QwkXMpRM9e3SFkixekVTW9T0K1XbeIF48azGZjqSdCWLHAIqGtNoNMNjEXTnuaYPBz6EcLc7rfqTorKumV+TudDlYQykYGL3JWoldynhpmf2hplx7MxFyh5cgu2EEb48pi9kdA1iYAZE4hQPaz/K8ZvaEewycpZnguOEbf39/rCel+LN2Hs+fBb6upcOp0CW/wy/EyU588OXhyddgmaf0ElAqSZhM2YpTrSlin6hj8z3Rjbyy9BgbP993Fd2PuWfNMR/ltQoWrBFKil7/0iVyG8lBLANN1Ejvx550gdddzx4QjeglOEE7Lho/LV+lP9d3zFY5xOrwDou6UGyQ+Ca+rPOqhbBId3zEhzEbTlFu1ohLz3FdGuDnE2HThpjyv2Vik9ptiNi3ycNZtgNAjexMLfWmEZmWnhTNzlNULev7FmwwE8Acih/vjTl1SjsKUQ08j3Ly85XnEUxCujttOleQQLQIuA0t8E8V0aPzgbZMgYyqUFfarlp4n3e/7v9u33M+bfk6hXUK11iU1Y1fXPmQaTmQH2zFMGfbEPcex1T1bBioVR3r9eiEDkv477JnIDg4bZbq5Udad0x7XnYn7hvfv+H0fm7HGr7o4v5xsEwB9KQDTrF1A7njuT+Rhbv
    postgresql-postgres-password: AgBEgXVjK2kGm4sLZNAoQIwsrayCK3tOKbxR8J1DFnahi7RABoPgPmTFwnWY6AzRIqiFxKrH1kVkYdIrv3JSL0nqOFLC867JxgFp/ZvXi1xLxKN+8Pf+m4eyy75bis8BCGBvdVLdLqxMw69RLJiHgwwKSE4Ost0XRzMIB6rt6VW+/nVD+zNCTiiFdjf2XwErym7nXlU5ZjDnDgOaFuLCu/1urZCbDPy4kpMevoPpNbFiNiR1fZRCnBj5xpuUvbeOQhq1QRMx9394AgQiunaTeLeFHUtqZgk1UFAe5NAzxCGoF+BjJQxZtmHHWz94WLqFRroWIzy/Xzdw4MnUcSJncl5fLgta4LT4kQai2DevN5qbTAE0E0e/MLidgPu7UWHqw/uZaSfR/d/wVyAzM1is2byRrHysChLea9w3nR3V5v87vDaVgQ7tZyRNdhjQff2WyucOMwPB5H2/w8tw9jvn4s+cM3GTgquPa9QgHMAJo1dGOQmqR37C5AXDg9HrrisNxmABm6QTLeS9yosBzL17pI0g0Tqk3cH4qxhZ24lcycJevF9PLoQ8u04+4kWI7ZXaWjG7nCzNZ6LVCkh6NvSPIfGdJGlLiEq1jZCpg6udSyfnTrm751lyExFk00+vZ8o0kH7oCQN4r40mYtpq3vbd4nikKmIxkY+N5xQlUnY/jcxlN0Jpo+y7vA5L+excK6s7t//WlYzyT7i783/k
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

