apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgBwxCU+vrq3B8P0kOtNfmnYVYLlf/g1aXkPpKmw58q/DaZ/pEAhbL9rEZCj9wewMWsS48uOxTKhORJd8HHQRHyTx7d4NTK9xcI05Uisq9dk98xL+7bLVB56feRTzl0puGWhwqHAFim6NvlxWW93JAIW4H5/OOs6qoEaUq7EzW1L2W2PhOTaGlz5pTMdK48U5sxR0nq6NFs+k0+qF2GcAp5K7vmrMv0/a3hIrHex4bVRukRxt4yaDBf55N31aLe2T7a+0WRKMuh8SutjWFzqqaYh8tg1i3TJbyNZxEVVMxlfbF2d2X0IcajWbnBgdJbmzefFndfFwmdu3W8Z6Xx6Gb6N3coEC6AX7+pcM8ORuYwNQINxKfxC5K3iz7mINQbzam9vqa7WgGce3dqDjCPTEZ/nvauPFvHzEocY5t9p8vE0j5sMyoAzEK8ZK2z9jRG6L2NPtSg2X6jyh4l/72nrhTDXbzgxP1DGqMPiDW7z66XnQ3s5mpYCOKxNDBhndElYiRYJ9+zw96lh6ioxij3zE3Dwg07QuFuGc19mQmjKYn0SjSfkJDYuZCaavBiZLlf7sVqmD+U81tSw5CX/Dm4jb0qyLc/OZWNxJ+AlggPZOv6p6WiIeQeGwom4XeOyHXmPFQfu1KckavQxjSfl2E6xkuM8ZXTNUzDQGJi/5yREx+4wEQyFl9R+Xq1tI1kunK0o8DW46Y3TyxDOLBdMJfIp
    postgresql-postgres-password: AgAE1Q3ajcwO0se4uQHA1Pom7e1YC3Q942EOVQXeiOpzg9e3GpIf3kNojPA5tPZJrwiUo9IgpVDycOoGXHLtly6ofa4pbHAu/pE6kIHSQYznXY8QiCZxVDv2cswIRLcdFOwu0k4ohLNW/SSilfKkb/v00zCBGxm6zYmoLVSgQRBnoPXiE4BQwwxb3l/PFKoOXoi9ynOs9kIlvq2yBfg7XHUrdFIV7O64kamHK8/PEc4DQTAjCOXCTFCacUI893zL3izVFw++MYBOGjlZHwS6SiutepLEKac3RB8rkCLzZTzaFSx5fEunamTe8Adrv2YX4DFh5PKgt2m7zDv27obKWz0H0pNMPSLW3IGDVvGccGGQWXW+i8gL0MsqTbdsOI7kv6LeGFWscGFvPIzVy6/yilJtyCl+NgowHPRh6W3fFJfyC1BA4DAptqavJKxjnt1VpLjznk7zGkD0SgtJXe4Wgy1IrwSajq7lr/mUBSoWHXEK9cAPY9Qf+1Yd8ekAchW6xMtvVbziR8V00gJsZQkQLt8CTv/L2fiydV4rvEnu9maG5B8pJBqZ2ASTPPIRzH9IIkWqGvkvxX4/VXlU1yNAGqJuCe1v6Jj9Gp9g5pVLjE8dLPnT37sMdp9zsoyvLpkavt5IaNjgXe1NuL0zzRmNNRSIBV80b37A4rjXoB01+um+cygRH8dNMdAkG9OHyUwee9HOJuDuR6iz3Xq0
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

