apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgBrWz7OouosB+mBZYeOM8T6cA3Vbo+T+hXvG97+itMwsJM6yxL0KnY/Jv6TX+iT+LTm6iLMyPcUt2t1jyG7XNYG5PgoRHCsAjdiQWpGFKH/ZS/oguoiVUT8Sa7QwarDTHE6tk3qRdbZFixGtNCyRpIFdy4aNoHWo3RZQUZxxwEh2zcXS4D0a6llu40ISbLr9o/B2AyFsud1jrFOO+Gl5DsYYuN8uVfO1RzOkHmPhMCJzprFnzngftZSxXIeQxfd7ZUMuMILHwMJw2YJNwFSBvvkvR/KLQhmcOYSmIc/7uzaw+Xghlc0AcqwxR9NVvhifUsJ/Gef5rXnS3wdxLl9JHgsOnZigQE45c/l0hWzPEDPYn2IuBYsOX4wsvWMtqpsyLnfcIfnBqUq/EVPUEqlNDzz1X1nb//f8GLU0NSuIJMYZY9uXW3AAs77dene8xvLdGCe6WpWfRQeuQmxoKd620pSIL2gVK75Pu/Ks2vMiAWG8dlrjGpnVyw+Y6dDU12kNSlR3ANKYxbjvUPqGZNal9TfBA0pZeETwTTZJ/kxDc0OM4hYuF0ITdtwO9rDyaPsByIGkr+MQ5t4DdywBqAotndCoq7SwOn7hhVxj/2kCktjlrd7rZILTMhziLE2pBJ/hvoMguCIhPwt4EERVjsthLw0+s0SwNNxg6sSI+EkdIEz+us8XqljdiS5rJeBjxPDB9IrweX0/2lbYw/1lWWv
    postgresql-postgres-password: AgACfJDMOdP+OVKFeaI3e/7CoJ6MLz9cJgnCG36Ycx8q1vv6fZUjdioXa68yxAsrQE+RAR4et4VX8Quqhvt1Qd++Gztu7+sN1GzuuzSQK+wMUUOz76FD+d2xpThjdL5SjXW8EVPctlR4lumc4j/OjkisT/697ZxXeB8PS/YusrP3JMpCkfvccgHlkjPq6odE5wd3N2LSj1ZRwDVuOrODjstpQhu4loCFZKJapwY0DEw34C/yHZbLB62dCWDCd7YxxVuhj21rMbTxJbrCoT7j0apZt2vWtVQ4oCTR5qP+j5ScluHwGUuT6lo3xMB5NZi7H5uh+1PMgloqtIlhiAMA1qKGsJ7I0jagnZfFRpU54f+UmJOQLlMfUf+6TH8RDDNuXrCf/Av3VCIGwgwF0/iz30606dbbFm+Dh1RhTsVseQCyxhjV6/wG1e9gKsvcX2aaFdVuMtNq+v59QzYyerUnXPq6vv8W4956z7am2L4uw8ClZze/XwkfTP9OzbtJx+W64lNP7vCd/YUGqddeRGyM825CC7/vM2QrkzWWdMgbIr803D3p4GEhFVFT5Memc7rZhaT9nuAWzm61CPTbgUljzxnlTDDDh6pMGTOYbehj4rsGZoEAb+xX9vzoIVXeHBkv+TJTdIYxm71yBDb7uWQJjpcqxeY/Png+252Cx/2gvO6YmfqO58JCMTWapzAGy/LNduddydohvIP7P9+e
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

