apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgCLADiwCF2OuCyTlHh6nN28OOYMDFN0OUR6J+WnmoqeQ0Guxk3/S3BuFoz/QMI7BSj+tOvUxpGPzCpxLTpDbgjrWIuvbUq42Ti7Uvjfzc4dtMKyIOVn0nhnCp5cviR8TatzS0t7S+Uigv6eNuI1RwLV2Tz7dP6RGwo1IFgoScRqnJ/SfEcOaiEAJN34R+V5k0jPSvuolgG7EaixzAIdxOesf3VcDQFUrN9mxT4MxMKXTIsvaB5TTOnkQA35YO6YC0yvOT+ekNGIdXVsLZCDCKMiGf4iGXIb/93Hijk6hgSFw77XSNyFe56SqUzX6ltp5sdDhEvGdGq9J06vIZCMUBrC4OiSU6N82LP0PVoDqnXVTBj34oTLNu75yVqdcFifJjfrkzDHd9C5KqVl46Cjgeu/pB9JVXIhYPBULsBqZSwXWcqKrTD9uMSZ66LDMC3MwaLnUkKH0LbT+IJODP3eRAK2vkycX21B7oldJ4xMLdJf+ZX+InpmPQdGlay3D13wkDUtkLrPwlW+39IFI/ooB+0rWSdzVuHMfS884rc2eZohPaWyuvNI/b57/4Oo2xCiFaDs6PcP2pXOCdcpGzH4nBi4f1U/7E+IDsHnHb3R05lkpOhsjIVLB9nBfXhooqQbu1COgMET4E8gWHPuWIW3VtE4ZenL0TYAHGvzLdph5wHA0Vn1JCqxzREo7apwn6g7hsFUnEvorlOig+r6wmY0
    postgresql-postgres-password: AgBrHw6DcmJDbMmPlpvEOuER4RJL7GxYq+EX6stZgedGQ5zH8mb/rOToGIXD0KnVAJaYTFxcgPZD+9uz/Yvvwi+R+C8h0U9y/1bcI6pwb06/djMmicRLlG3ImwWkQeD/I3MB2U1zRlPsgLylWn8QlmObs4KKOmQvpuUSpt+YFc2YNryR9cP+kSN8ONM1Xl1OBJ9FtpqpTcuU1pJN9130DEzMsnVkG58wIL26fRpzoqqeJ+y2EUQu6q5FB2n8J+AUDfrTgJVkneqK43Gkp56ZBU2lbjfeO/i8HcWwmnl0IcmzPntjjBF06xLhfvLhEYIgWKkAY+1BpLveKk+jPVM+pKclrY7Cn4kAiVepXAomvPi+1DYowRX7n6d7GGGVGQpPYcWElcLbslwnEgq7qpJnsWNSNXRfKKyxI4tN7Md9Idicd4/rwvwL7hDLBfE3pe+867ADQLhlBmbkwJrKPuqON78CqQX99B9So6Oo3TdYPghm4P5XDu+cs/iLcbX/x1pAdV9P1L3/zuo3cdFpkfmao4OuEUrBG/+d5oNI04kdbUFPACYUXQyja5jNC2qmySl+A4+m7a+iQiZ2hv+C41jGkkgcK2DNgodJgxsjG1sO+Ruuqh67Z+Mv1/fJJlgPQCkEYmtgH6b+cJKDwkXJ2c83tJkWoMsI/MrWlWQl6QA9uXB2rhn84TfT0gbFZGzbDkvyqVqZGaPLiUDyOwGo
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

