apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgBhsb/5nMjNVKEsvWTFvBv2gVIAm7U74+AmDIaueuEMCfnfkH8tw2diN/Ov5+r1E8UkdnDmFzbFj9ilPyZ+cCIwoEAdFC4pI9b7GUvlbXLshGeBlQoyiJup3iIE1OCdZ3tHcJjI30jP3LUKvXeqdlf3C4X21r7RHmWjEVo8KHMWxLHgsCjmHVOQSTxjHY9Rdcaky+mWfm+VfpkV3Uv9Ddvdwkf0ZMIMAI2bNU40oFMOkYRrpLWnPyXTYbHzKGWW98oEvL5m5ulzHpGJQ/c987gST+a7Wi65dognAtSEk2vh/Ci38/z7v5Fh74N+QC6WAIusY47jbU+25f8iigFrxSF9QJ+FqGugvZq65nG/JYjSfShEI8p6ETMdbH7+Y5SmGAgI+kmMZ2lRVLoQXVo6Ai9mwSWWg86b4t6nsI7QH9uxhzgcHWnmzi2RIxTEoYZ6UUl94mWOyk2KXJPcC4N3+4q/ysnUUFsntU1WbNXLC3ZeO22UTDxaCbVApbjhUSy2jPKXs/RMPhM6vD/s2qFORU+F/3QxO1WUNPapWhIJXxw+CeesGfw17RmjBPuRAtomNDDYlIWsoHuXc/1fXN3iTg0wwz3TgwoKPNZwFeN2qC0IesZsI+Ezdz/j7n49CCCR9vVNCdMbhfjIc2scVfJ8e4Rp8Q0I8YV2QIDPBOBUHOZmSufvxYTKM3mLJPw1uLU2mpvSpIQoDxhthB1MAGpk
    postgresql-postgres-password: AgAHcxIiXBduasbhYTdCc0kIhnFVmjkdWXFYdaGanbi6c15pOWrtF9qlzrAHGlYOpE+tVMUXqUFqztBi+2DMPWuLd0lyS9bV08SkqjkvUzmWNYOcObtiK3xlBhVTpwhgzKG24qwJy4aBpyGTEExL1A+O3KVqexXuEEioW7ihOE0S2XIQ/GTykXyOXWBh7z+yFiNU8RK478hS3DOFS7yN2BqHgyjubpeOs/+x9MrvC2Nv5RY4QW2VCvZcVlTpT/XaKQvHxe4CVYVg1cg7Ifqzh/yG3iH0hZLGYZZxonM2pKOxMJU9uaXPU6ue7AacJYw1BfpoVgz6J7O7Cc+UmG/zTkQYSL6bh/V/k3doCgB5zw7oOWnLwg9H4NaIDn6l2ucYZdUyw1w5uhU2luX5ux6p2gf2+oYTOHUZKxhU1abdkvEdxQiEQTY3dA/VhqyfpNkyB9Lg9xMPB70wL8nbDyOylG2j0/JfCIzEluplRkPgOonZ4RCardB/6K39gag3gXqpOWF9hgj+nNrWNWPteZCool02sSb57r9cgXvnNy4ZTH29GaZ6JoB0pak3YSFYZ8C+TGPzICq3v5POZ4ZvWNUkN6Cl/e9Plkt/qBgR+WSJX4/eo3JOc2uC68RUzVAxaR9Me0rleR0WQXa8iWgSynn/hrWbxztul26qQv8PtMLcDWjAqspqMHLxQR7OmKlVJ3dpAkru6PK4DN6kvHPZ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

