apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgARUgoSaumyNV5srvHfIu6HvjTUs6s57FgXDk/jmemfXiX+lblKeLwdT5nef3seuI09Ems2e//MR09o4rfm9Lr5p/JB+PxeuYsAMKdNbPhab0BTyyMA5NO99Q9BOaHpIo1pDZrgUGcKgzddrb4S6YSrUAwZyFrj/MjYX2vxUqEJXnt5zBJ6vTNC+Cvjnre5TrIRcHJDN/p9y7Xrcp6Wm6+1kSxOLgzsBqVrrHqlYmkjbDDtHvcf2Wa4hH7rCiNHHAzO17pq8Dc4nBNbYFn4y8HFX7OEAsvhSa7S85dghWjP2DsUmo8LPG2TKcJNoGGy9sRohmKQEKbiR5EV4wuextrrk1BkCI3k2oaQM21bHzMwrTIUJhxWCPcFa4oZc358leOK/HALvXdE5ttrjGY6R5TOJ4smyoBHV7hSz+585+3RouB87Ai1YZMdwa9rVJIcQ7bdoJNcOyobzS5+2++QZYVjkdJ5W95QgwwjEWUDF0Zz1TX+2NiyMNxLQUwkdlgox0mY4X1KtNcTm7slkX0ErIi68HbH7NE+TkXvM6HGJBOZ/aeSu1znckmk/N4HgYo2QFwrnjz6va+OQ2JVLNXE6oJ8gwM1h8fwCRywvS+XtJ+ik0jZuY0rbbjZZOWhF/9epMeyNPbEe385cv4JBnthOLV4trVvYmhcN6q58jwA4swdObEQ1zalG0KeZ3b3niwwDwryjd7lwcdl
    postgresql-postgres-password: AgCu2DshvJ4lf/yfkBMZC7iblcb6DM5Sg7Iu4VSKJeu4dGQmKmx7PpN1+DRkSwtqOGK0cViF9weAXNE1f1jhobKr/ZSCINnIAlFdP/rehV+Y7q1LBE03wGS6CWiidjHLj/NvMN0F88hdeBXdkLFj6Xi//kgoRpMBAVonoP86yaC4wPjZoU6yDq3i3ms+L3gqdqjQ71SsbFmSH0tOqRNjay9NBx8iqQ0ipb1AnlfMPbHYSngt3Pp6DBOcMsjIPFmjrYMGLkUsVbM+zbbDuPs3H04+CjtLdxodWHIgUlG5xNjX8DecAeeNuypYJA/nVlksfRfLhty788g3iy1LDmpoVSqUY0FP8iVotIB0nDkmFGFKcIHzyPe0NFu5XhRQP79XgYehokVB2L+RIF7nwZHT7O86IzHAJQPrtsa0ft9fthgbW7px95IsvC5N4lxpJC5ZK2/AbW8Azjzj3iHatvcRwY7OrVrVBhQG7bXRJy0IV/Lc9d5UgassBx58DLJxKzve46mPk+zrkA7rVhLEncLU3RPCJRye65kY+3NEbC4JuQ/EodDevV/JICVBouy0N2GChUvQtz290619OC7n75pZ9r+sCbV0aw/nbGRMiX+zYG+59bUjDdIt4ogNdA+25pTC3tIB7x2H0vHPE9HU86a5XtFpZucCjoLaocDH2ndYMuoMKi4y55zisbtEflIgIFamz9ttACJls5sO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

