apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgBwNVVznC3kY1M1PdbdUTqHxm86lC+gEMAIE0we1e5C48jG90VQS8u9HuJv0aSDKnxL+n29oy9MVaZlrouZx7dnccxUoua6r4o0SCZPeW6QCWmHbwQbyu3NJXIszaSB79WGAKuB1duYROt6EL0fFHRtJv78NlDF1F4/UO3OXSVAUWRJ6oe9ox6+poKOvfb9ooxkIYHw6JNvhuyTJuW91TP04XjrlmFN/QQ+8135nVRhJdlUr/RA7kDmrwsmom8mMz0BHV5h2v9s4rjLyplUChVVOuxFzx+p3/3T1swtuaGRw8DVoIW9M6QAxYOmcEJF+rAX6b6ApNURGW7+Xx/mpnQohMPM1McwFTnpk5BrILMJMErgMNeVMSDj0sJgJsYXyHv5aDEwyWyxRkSLHKZO98/JE4TSumRBoqjnyo4S97zMU+yXKVUzFQaecyzba29ZB5L348YCk/uIy61Vb5wJAe2/ZpnznCBJ6KYYTHUPukW5dkTDU0wvuR2PUGQXnYNx0SvgXZwCJfXeGqTAK+rCxy+qDGyU0Ma8uOnS7E88SVW10NT0av+phHd8eTxqs13a9F188xeetA+ze/DVGf8hcA1N7M7OnM7EgQGmtsN3TKr4FlEvnFfOyi+GgpQlXDpciP4uspHcFkXZ0HYVYu3G2v4/CEbv0GO4uxFyp3Diph4Q66juzYe65pH0PiAGWJbAsZL7c+yVszPKjN5lrqDN
    postgresql-postgres-password: AgBB6osO2jeQR8yXok8vMPS7WEG3tA3TwPPgezWY/+i6Ql3sV5WSFZV0PusI0YVMmWRWlvxrW2mpgd1LA4DOd813Zcs3x38tZgimaHueEfOXViQu6gSZergUmQicSl8Bs27ISjcyZazL4Y1h9JukPOQ49x7E0Mf4blAQWn3dCzZrY9ikZJWtTX4eMO6kmeKdu6NJ6hw6D6ZgSp+44ihEvd9+Q9VZhuTPHFUy98c7ojjLoQAHLxWdnVjmCqTyDNT0iGH2BE14GcmiK09JHKerLmcnsCsRh7HuhOxuemLX43vq2kvacmZDCEtwofkjjkupQ4w0VOlT66z6ICt47bkxz3GLvfuIl1WX9PMRFtU5LxKiq3EUbHcypKLI2XyqJbWY+ke/f/VMx14Fn0urVAU+LwNlv+sDRsN3kdgznP1QAdrqhwMI/nvQw34WJDH0W9zuN4OTnUd7oRfAW9yBLzNpvQFSzuUEpSTcrECY32HvGQZVodpB8mZla8q7d9mFLJ7qcUH46+OzRajVn6xncpr6B8WATY9YoOgeqUFtX8Nn3we5v9Kn1TPHPFxj7hmw+99UtCNtESUdSlFVK9TuyfPKcyYyvkYaxqXFZ54uZRKL87QhO1fqpCZaSNk5oj8ndaaegNJePhiPySF3RfQ7bn8aW62ssSJ8q0FCXNAQWxjasmbGjdwjA26xE+wrrb9hjkHBsfyL9AHR/dFztzyG
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

