apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgCSAC4qyBrPm1XjZEUPZEpl+Bgz2uOLUULSt5w6mZVmB5FTYkbnEV3IeAyV4ZgclnnasJrRgfDQQYLv4wA1k7pBmaCoKTudztL0saFGv5eojg/XXPtJCzbkSK1sjClNC7wmCHu5R4fqXdb4ejnIE9wkLU764rMti1uqHOvOPvRu3A5H6ahWtfeVO8Fh2THGxj+UwHNjKEIQVZjJN1aGSbOz4UQYrg3NkYBFtj6frX/Ds/fZeyKd0SUMJ3gkGqZXNDWMHIwJTGaM1WPHTLNwJXO6aYY8dRzFDboscpr8o8IS15TmXjK2dV1/9QIxVsDgDZ7o9ScKJmylOnR5g39lCcB+TwF+rylG3GLFCy9HZN8ywWim6H2oYKor9oG94CqnCl/vfdOiqVIIFO137L2/p5IngSSp7VTBTIClg75JHM2BPholTMvT1enF60Om27o9jFmJG9oFRGhWrftwFA40ozsex394P+q8nywSqq5LE9mZY6WRtd0yBjeDYzzjfmEAu86WhPTqhEdMvQEEvpX/NRk/xdf2X7iPqI2H/WMlpznkUbffARgVV86bAPjIg3su3v8DF0m05Qam47nXWvZHKPZP1y+NsTRkmoZlcu9YSoMOGnyV52mE7sOrnSMbBDZqdEp5J3hX1lF0a4vvIqL9FYEwII6NHfCrKri8l7KoFLUUe0kz7/0+CRSvlTesO4ylIFzHlhICua86IKxUC9T5
    postgresql-postgres-password: AgCBMMf44GEYsxxlf5FHid4LQP366JyRNMWgDlzNkgjOTx6wcdgs69IgiTRqdK1L/QLvhbpV0D+BOjMXjbZ8SY1XSdi0iGV+IqR3/LBa36OWOmMFuJhEtGhgN3SmLgz+QHlvM1HQASqzv1Z1IX+10F6l1/z48swV/leGgDpMzRrdUFKqtoMIUgH3NSjS8dtLuxL+W6xJabgOAtH5sYFpfScfeI/a9okiCxf0UDaeX9E0OczzV0gkNKLt7Q3+ZYKNQxBtvjRycPgJA18qb97Iyytmb86PL2FrU5FKSh6iUY+gz9ZYfFdVuub2ZgzS5DyfJxX2McXjOhO+GMIC+M0ZbixTcASASBdLQGLl/6YtFaizw42gVTghUSRznf6SH7ISBB74nS8F725mlqXnBo1pEHzh4jf1OQuwjGMN9o/R7jF1y/uBXOnsF4OsFY6xbV+VPf6axuMDFA3iRbFczzYG8GoBUsGbDH/X5nA8mJyudnVjXLOYp0jJ6GqRPiyKUHtcm/Nar7BIrwYIjUOQBfsGrGTXCXY4+TS2O62wLfXtYq4tWjmtndilX2VDSBFHzDW2RQrCINaxKmNfPAbYUItRkByVJ1QlBCbFc5BfeTfHe/xuXvSIjSRKT0W52LJUqylY3hSIvFQop2Dw6BY5d9uChnX5KVl2MNLkmJNTsvooWIM9oVCD59QfT/bBVpEmqoheSF1dKT+71ZuIotOT
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

