apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgAqEEf9UY3xs1ncsvTrQ7Pz1lIV7e5x2Q6dUmhXtRn979LHYVj5XdYDKSQPECa3c8rRgcN9VK2HlNARatc/vcvKr6XsU+MDGpX67b8VDPUMr72MAG+vhgvF+ABRBqYuKN9qubXegqnR1aI/q5ooPkb/G6tUtdFtQFESzyqEAS5HfqIGe+6fKSVfYOZPgCtfrdQcPG0UF+wAiuPjGkgR7Wct12gmaO8fFajxOvwkgdWduAEEwv93SW0ZonCQ1M+XzyQOXQq8iifpzvUq6u9gGK6kZgk0CYcga6+9SYXCzRVTy7/uOq7AS8P46/SHK21/SjXajCfLjjNqpy2VRD0btVvHJL003otTkBiObcQeU9LAKbTupoLxrDqOGnCYM0p3stI8sdy6VrMqGXaoSOdC6cBMGqgQmhQb30bC/2PoslCJiT9jjSXK0lAAtZ3DqKPMs0CXq761LThzyZY2ysnD33dGeqCh8AG4ozCALGVUT8M2HZ1X88zsj5VP9T+BGkxmHS0mdGgcekC+uTP0SrePWSbynbkNt9GvEgOoQ6TcEpiN83pzX65M+LdGgeLOh5nM3wYXbEnipJ+zfjlXPH0Cj65P19LJsf4+RbyIIujyeyFuwkYgjChEI/QV0DOsieFLpmhvt6qsx+VDh0YJrSpHIQk76syp3JBPEwKy8kr7zcLDQvkb0M/bZwsMf5uiQTtuBTTQuUbp/XUK+6b2rDCJ
    postgresql-postgres-password: AgBtpHkBy+pfH8aOoZTytwGrpFA5HuFX6lXW3xpKKa2lUVG0oarG6A9LIrrmg8KJXCMhTC3tJgjT+I98QDCsvJ/Tyt8vfj9OtwlME4gyYsLYbWvvoEazo8RAII2IdaBpJI4zx38qzceZQVQw+9pOXOrNOYAywtyuN03j1Fpvu85TW6DuLwQd2uBddlx2Fnr8UTihVx4UpI9FKcPrR3LrJlb1IxgkzDV7FNauhUPQKWbiJi5WG2QO4mDND79QzdyQdkfbjOcmRq08lLDWigRP51WrRMEHbrCgDv4SV2t+vtar777onbsH0OqvK4hpaYAkj1uh6bzMOi6nPAcFB7Le7dJE5qx3x/lOk/IzBI+HzMVOUpLITsar1KDgUs+diJhECXdDLaiwTQcX3IRfwkn3f2v/ER/1LG8zavDt/9aYYfK4c3m5jkZT9ov5lIO2hFnccGXwQ5X9NophJLT7DEW7tcHbb4KdLV/G6AfWOARIHZj4LIht64uGyjDnI16WGY/yrjVAjcOs+swFe79SEvx1utldMX4gk6ZBiTPjUBXUWoN7hLNXN3lTIDYkzKEIsVdWJv4DHhwPJmLzRwb+6Dj5jTfj3v/Z/quAbzzq5/GT4KG+ibxPWdgX7qmTHgRHImiesgtrN16y58eh3R9KQWto19VcJ+BMRmT4hnvM/DpV7fev2hnEUL/7BNG0R16X18QSMeccfqxjBzPpbKTd
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

