apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgBXAvG0Poi6+Ps1f4L77oHehroNSFnqdlehu4t3v/dQ218HO5Kikza5Z5E+FvmdU/OmwPSXlfQstC2PxMh98RT8nQS8trjMbS4cF796GYz0NE/zAPbf0v/BeHj0LBMHcnZnSPh/cBLDggmChwXG5whyaO1X/NHAMcRXbXF+qNe1kUaeHM0HxJbWQWrMv0hMa1ZKh3cl6hKuECgRkZlPN3F+aZrR4sxbC+AwxhqkBtNlCHjWFCrufxb6Tq2j6LHxlBsh47hAipePC67Yo/EzsS8DCvQ20BzmfZ8BPEuAZzx2L75idSYFWKNAvZ3P93lEpQGi+hw+eCmy3+JVtVoWQ8JPQecjaDPVc2KbKvtrk+3qxBU+ki9cF7re1Hc/eweeogUozAUDx/34pGJJhPXlyNbwtGuHerrLNGZVVrmLyHIqt8+9jU7cCmYm5g9oSm6FT9TD5axWnPXti1MAR6ALmXunzR1jEToqPX7DlSYdjHCtae7qq8HtTt+g81M0qgAXRO1J9NDxOO/FjmxRf6KygjimQKBkw5xAR3zDoSWCoSAI0sr7URFYcrqAyoNlikV75eHENj93xlI3uQfWtn1e5gAe7jOxTCvQUsr9MMm6niPhkQyER7wU9fa8M057Wvl1sf4oeY0j5vvywMuv45as6irsQpOQhJSKAQ4VbPmS6ErDJpLRn7hCncK/fl1jmJhom0MThDZBvsuvsLgrxfp1
    postgresql-postgres-password: AgAt1reLgAlg1J6MVjD3mBCWJzb7daQUTvwyxpauyYCUK5An13VMgDZJ4xpES+qPAXpyz32Ke3PkYwBLyJPEHlD/iZRtUQ2viuO1vzO4CUWMk5CC5uDER0JLC3/3op8tuYpQrcqv0nQKm9tTlkss/0x8kI0NCBltD0hX5vRJ/AjwrCpU4I1rA7taDuOoI6oI3H0eRvWGR+Om4jibT1Gus+3Jh8o0x/igtza3Eru2ifH3WVhJRTVarr6JiCwaT0sDGshXQ+bOi2LXH1J7U8cE9FJZtLnSD7TqHcCSajmajAHPdDX387eUfBV/KgwTjjqeIbGexOVJcOiU1cTdxyTTper6u/7C3wDLrUgae7kJ+2TtY4jrZCm3v+1e0W2hQ0zlztzKtD7RKqTPSRiKbljiJ7PyvU060sk1uzkk5J/uSTwA6kYeUT3TGb2hKQN1R5ZYbtkZs8eJEslc6lyEMpjtVt3mSER0n9pHlYMiDluc6qdC0cmJbvGm3WaS0tLdYwHkoM5KvVGixlyPEHo3bRQ3EgyAH7eWdmD4soTI679fJ+yqYSIsy+bg2ArQDPpwsxQeSyDwruvtz+YU9jdU6QLy56JggWvivT9UA6mSqD1UTHhLMxthiFqgVnv0jrImOP54BfNSWjTzpDfwZawv1cc+9pjnsPwOJrFNWg47almj/oetdTQVlyiey19HOq6RkJgfHkcNnBZroXWe52fj
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

