apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgBdi+bDujWg8G7gMYYsndAYtlq4oS7VmWg5gFgH/zuVsbzNvdyqNaAXSqyMMldNPQdNIZF16Fg10M1VqRF4hPkcL17UXfRWCPJiaqISfcOzGSLXOoyl6LPABw9aptrBA2rGX4dDNj5R3K/RL4Vl/EPp14MO5H14mpdbEGlIYxtNuiuwLNlXdfObPzHeiP4Jo1fJkBFFKxJQz2SpVC6hQjpS2MUX0el9nT3gG5ud1YrDVCM6PIoFMWGCT//6kHtazS3kKXmCV3dcLAW+43zjOvJ27knA9WcabvmkiMnPiow7TsavNeSykP35Jx2KZRrE5UtpnQaQnVO/0R2STKScETiIz2UfOSC9lWUb/Nijqf9PMa7T8n/6Jac9SeDJgiOZgQEhnxOhyDRZJkNarWT6rZ8QBEyRtIVztluH9qgYFTKN4vAV99NUS4PQ5G4F+KRdAfmiOG6X5SPgy9VdircBElVJzLRCKTMmqb3sxGznpFEZHrsrWVCJzGxfGWApWHX84N8KcVQqCNADB33KQGyAmO+c2O+zpJyRB7v/ivSWV778gYEOLG4oXbBD/SWFvQDsXA+ki1IH2qmlMnsSiM1mdkd3jNLoLiT5AFaWZAZ6tZpwC0kn9d8jVabIbDjw6RLA5Zc0YyxEEuicCcK2TGayXiSkt0kHwgQGBArFju/jBie6xqxhYvJo1s3dZvUvC5vRgTGyn8UdqIGiCDjHPTVW
    postgresql-postgres-password: AgBjpO8iDCYUKMVQsLayeQXus6BXT8A20+6t08DUuLmiQ+b/Kfl7DtlbEtXxvW4pUeiu/92JDSp51We9l0aGHDRKdEdenrFHWkrcjkean+5QmtEzUyHvxveg8tYbTQ51ctERvZTL2HY2Lj0N8kzAp5VhevwAR/TyeNPvzdsqxun3jzZjF2iwm+GpQzaommdFzOqVNcZ5ZJrb6RGtaOmNGEXaZMroML87xmikbPzWB9wfI8WehheC3O1wuOanx51egwSTpvs8UTS12+Xu2Y2Ym64LauhA5KCd+qYEhmCiY+w/IZpRRriM78r2Tb45lxbb2M/IgbwRRlqut6JlzLFvQqJPB4ZGYKF8fMv7lsYVQE0UaSXhHnEx48O2H+Ph7Ym+0L1FmY+rUgNd+3zZVXQ0ql+DjYTZCQMt5TICOOaDw3CtBLVxwJaUPvVwfaiqAv2CIRaR/PZgO8bsTQDqFNV4Zq3LPs9XGICb5eGL6msvmCXoIPOyNqrgsjO3Wj9MkqLJfpHt3OBXOX/Vd6N6UDUArlH7UtbAib6/OIRSVZVsSQXAtpUFyG6Z9roc3psp6rzTJdmJUAuDQul1xfWjDdQERHvvHmyFf8GbcUogMNg1sSuIcJfgCfNcUac9jFmcO1dI3CtW4yyGU4Nuyf9wMdxtFAFy0APwxFAdHNsDa4RsMG6jmji9Wx5CsAexwmqBv0tl/J4gYyiX9PMwxa4U
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

