apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgAwRVx+P4s5X5orN3ykszL3eWSERaHb/gYwheh1xoAh+bpx1xEL+qXFIZerJ3kExrjv8wd0OklMuWg9Xs5Sp6npIB1SUzVQq/JfGETogJb2milutIHRcEoP+dkobskae9kSpFeAlcBQxJLd9C6kpTXhmDHvPPQqHIKnkJRl+Y0jQID5och5NJhCZ7t/qCh+v1/3xfCUOdC9YHOyAbFB88HTCQwhxuNNtk5zKf61i8ditmximnlYmMUM7l57tttb4kwAAznN8QlC3WHOa7c0zDlWB/of5aocnp/0o7o6AcVuM743GNwveQfwadnm6Ru81EwHwt53Wb32wP6gh080gJ/UBu4GMOa9iR0ntskKExXBVwGtdf3YRnjTEg675PvSi/ztOlu7HJFdkjOx7kWxPhmv3sxOOYouWgCzyhAqYFWfTQwSyUkABNFzv0HJQZLmgYa2bVPbAKg2+p39LNCj9xqTaDul9lNR9a5/QWTMhNaKyHdlTaqAbbEda9YQNfpC6wKECC8tt3n9YZYtizdoahKwIs/mb1r+mPAjj01gMFimqNVJaF1pp+Wchrz73/sjU9yFX0LPi9MJWy5pLathtVW/8pIcPDPidp8TAg/LcM/LaMzXSg/YRdBmNLU3SWR5mCOAcDvFLK3et3knuiLP6n1FmQHtUrDk/i+mQ7OSmiXFrgECkWtjR70JpD9i+CZ09yINMcS+Y7QLdVDiwfNB
    postgresql-postgres-password: AgBD6aYq/urQZyJSSTCESQLfFKfxbs1DH5Nv0+zwEE/w0V7HbIG5NW4aizBT+kQKB+RavABPFKsDd9NJL9fbKBHjj0iS+ywEkHOq1vQb1NHSWsT8uaLk7i3Z+oGGMf7Dn1+1J4ajm5NNW6NK/nyNXE8W0OGCzihpZFRoIqxKFTJQ3VROgHXOpx74Z+thD0Sx0CexmxsbI6b5ASUBTunIX7QBXJgk75ka8oC4wBIAC+eGCegbj9Xqav0FPNpuhLMwlGUETdUeN+zUXvTo9oFRoY4oy/oHUkxklnyn2LrU9NV3aVJNXmZMZgha0yAR4sh3kC+SyZUNZXI9bHjKds9ft//2+YE7FqY/yWFzJU3T0SJSNKzSpE/J7W1MM4x4mH2gAm98rS3HDNrNim96UeAxfxeQlinX5dOg7SIUdP162sG4YxvG1QZBmi8El1DKRFdm0BwBUV+eSgYEnIhzS8K+Ti2jQGKZWPWxTWU1+cPEoMj1kdzxtnFU8r+kpakIh4b7zOrTGb2tNUkKvNTsRaN939h+DySo3zSaI33eMWCiazH77Ty/1JWZXxz9w36A/2BU2YXWKnkpLVaIhuj8hL+a8m7dsmyl3GG+RutpPs+pJZmOu0sGxDcBnaY53SFXgzLBX8eB3Os2mV/cEMQvbxZhFW+ew/VE+Fiw29xDCmT2Rp4GiMLIoW6fPucHGurtlmV/KcV4Acdjw0vE8VJX
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql
      namespace: keycloak
    type: Opaque

