argo-cd:
  configs:
    secret:
      createSecret: false
  global:
    image:
      repository: dragoneena12/argocd
      tag: v2.0.4
    imagePullSecrets: 
      - name: docker-creds
  dex:
    image:
      repository: dexidp/dex
      tag: v2.30.0
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    env:
      - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: argo-workflows-sso
            key: client-secret
  controller:
    extraArgs:
    - --repo-server-timeout-seconds
    - "1000"
    - --status-processors
    - "3"
    - --operation-processors
    - "3"
  repoServer:
    replicas: 3
    env:
      - name: "ARGOCD_EXEC_TIMEOUT"
        value: "5m"
  server:
    extraArgs:
    - --insecure
    ingress:
        enabled: true
        hosts:
        - argocd.apps.blah.cloud
        https: false
    ingressGrpc:
        enabled: true
        hosts:
        - argocd.apps.blah.cloud
        https: false
    config:
        admin.enabled: 'true'
        statusbadge.enabled: 'true'
        users.anonymous.enabled: 'true'
        url: https://argocd.apps.blah.cloud
        application.instanceLabelKey: argocd.argoproj.io/instance
        dex.config: |
          logger:
            level: "debug"
          connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientId
              clientSecret: $dex.github.clientSecret
              orgs:
              - name: blahcloud
          staticClients:
            - id: argo-workflow
              name: 'Argo Workflow'
              redirectURIs:
                - https://argo-workflows.apps.blah.cloud/oauth2/callback
              secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
        resource.customizations: |
          admissionregistration.k8s.io/MutatingWebhookConfiguration:
            ignoreDifferences: |
              jsonPointers:
              - /webhooks/0/clientConfig/caBundle
        resource.exclusions: |
          - apiGroups:
            - "velero.io"
            kinds:
            - Backup
            clusters:
            - '*'
        repositories: |
          - url: https://github.com/mylesagray/home-cluster-gitops.git
        repository.credentials: |
          - url: https://github.com/mylesagray
            passwordSecret:
                name: github-secret
                key: password
            usernameSecret:
                name: github-secret
                key: username
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, blahcloud:k8s, role:admin
    additionalProjects: 
    - name: default
      namespace: argocd
      additionalAnnotations: 
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: kubernetes
      sourceRepos:
      - '*'
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      destinations:
      - namespace: '*'
        server: '*'
    - name: cd
      namespace: argocd
      additionalAnnotations: 
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: kubernetes
      sourceRepos:
      - '*'
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      destinations:
      - namespace: '*'
        server: '*'
    additionalApplications:
    - name: bootstrap
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/mylesagray/home-cluster-gitops.git
        targetRevision: HEAD
        path: apps/bootstrap
      destination:
        server: https://kubernetes.default.svc
        namespace: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true