apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCndTIrhpJW4j2ZqQyIQNlGXP3VEXLad+OGvrqaVZbDcgaRHyV8fyiM6ax7cCY8IYLqUIFI4sdIVwvAYaLuQq3iWr5WqJ7pHmVzebJ5gpPyBp9izQf1Fmisfo0R93pf5bovvuq43vchSpau0QbskBqbYtF6TuWE7iE9NWJHZ9DDaC2pnLHzSeOUc7GGwUzplV/f8BS5BgU86Q0sr4dOQENYbr72uP7lDyKgJ2BQRnCMzkVSNngjd0U7h6J5RtKLkCC+Xtha6gXqHBUxlOUdIUO5huEtWXDjKV+B9X7cNVE85jVHorZ9dTJpWXAqYmaVL6b1Fg12V6N35RodIjbiUQAtUU7uBOx+y0a7/0mh3oqQPnszgOL1RShzP7dMk++390mh7OGPhPo4bvuf04aUvgw5Lrm5kdN2s1Hky97U/6eW4ExnNY3kwdsRTjpZJ7vc2oEfJx2V0NjfmKMNLqKrBm2bDI/G46viERrjL0zFw8kN4pVd7h46BhCRmO7ibS0pa5Pq9fH+XoUr5NSHBWTYYi13PKOE0sGDs6IwK9iIT1xSgLcg95BroLJV1x8Qg+WfrEOlyYazexMeJnnBZLMLOxZ9wgp6f698HL3lHwT+pw9KHM+DzTg8aA7HuYADWJaCBfqyY56BG8XaCzz7Urbhz84NnGbQyH4O9de3UpnhSVKTWTtSvfw6qOzf1Jhq7pfnrligKhxU243e0KsuGBUbgCc1oagitpX7mg2LKQSYRWVE6+KcXdKVVqMq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

