apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCGOk7zQhIF0FNKgWmnXfAYkAgvUGticteyCUA2gGRORR72Ty+oeaMfl0QtjijHQUy1vxPNf3Qpt/afSJlDVAPcFom297eDIKAC6HXl/wQmuAn+ByAoaNPLy37iY9L2aA2+AhqOMzxg56M9q3DjlO8u+e6XtQsbOfKL6mq6DxNKr3PAhhcI92VIp5t7/Szq+qKkkxqhXV6ABGFZH+zmGltwmeOR5mIfv9jCtTDFbiMTsWR+M2KY56v5+96Rz8vcLP/UsxjggeVB3q5g7x8E+3yHT4Q49urSOtKlfpIIG20/VOm+HcYqwiLQI+d56Qau6is1bOg8MOLsbDzM+/H/PKR8TfYciKyWh6Mjx9Vm6w1F8/7sXo4FNZjDL98zMw3G3iZQKOHdrACELTpHMGtt73G+EthzjMjwJ3ZYsZB9fogWiVupNUK1MZit59v/Y31AVZiwmHpcvdrz8dnHLcU5Ia6VFTrxzLsoIYasBUhh6W307awHYKYF6eSeUf6cGwQt77TAN/pJEjHX0oS7OyWiiHs3nhspB/79vwjvZd6Uue0+WYMjXZnGxTejCGSaTMXoYrZ6o0seNssHSdoonjZlafeShKdYHwl2mWIvRwt/UixB6VRyJ/U+CFUQENMLFomh1OZ53SZpoTDceB5UZQhs9zGo7tEoW6IoFdY7xfQeWVbq+ILdzYNJ3CK1KlFIxE5NkR7Rp7FEiYxxT/+c5kTxaoVSrNzBKpk9spZnI8hRcyEujIBHg/MHq1wL
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

