apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBr588yk9d88POUJhACOCo2fa6KTJ1xVy4eMKpuv2/htgh2ySCSxttisEYoZaTJ/a+moAcs7JXwuTknfreN9BEiqjo2cd5cq9qmfZ0WB0dKGPOdGbFvK8tze2Jl818Br2qZxoCnnWQf7oGET5xY5lUo0qUDDHHt+CnbcT/XDXChdd7gZgP83EbvE1M8nENjHFjUVDbIZKtz4DSjQF7/kOF037LmI/1pEyHqh/GCxBFMQTY0qbd1A+7R1+GGHlnCncwuz303wyC/hLBZz4poM+6F6Mn+VyHUCFKn8LiwLP/iCD8wzRuNrX7UDVynK1d5FYhBey3TAsvT6V6x6uakz1ciznbfZV+xnAtgOBQydcD/+kBbDEZ5NGrEIS+opektqkyc+oMW1CtGQwwPoulbjXbsybX7K7BDJlVoPZzPDHLBP0lRqMwx2hLHMi+UJziRckzj8Fg9wjsYYIcjKCLME20FyYEn1t/PHSPq37e721wT9jdxoxKGVcw2wyhlQLh4ZWEMNkBE5jFIT67G7Zx2FBMtUn7guECINUzQPWL/+NqH8D7d1OM87Xcf9r/XXTw3GsX7Z4uMluoJ4xmYl3A/05VjeSowMvEb8I/WHsjcmyJ6fexU1PtVmE/8qBfn4s/TCbYEFYADS8Uf85FEeqxZ/UjrDj1D4d0kbwuR9D9aYDI87phHUTt5qaNK/7yvRJ8kAlI4cDmU86qxKMTFiGZTREz3vz+nLLKyomAa7GcFXkCIuJ4pbV52kW+k
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

