apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgAcf0FYz0GcmLHv2c+uLjIABnNBlV6OPRFXVtC4gHwQFyLq82BXmWTrSsHnm6f+vAqXjWtbhBxTu9VTsWRj5MuzsyH9rHBuouiSR0nbNEYcYRWwqIg0BGlWITjl66B3YdapFKZGE5fwMCJWWVI13xX/MFq00x/JxX3QoCFu8SCyEPWE1JlsxNT8TEwuHMLsQ8TNF12RA+o0jclG5+FSsuC7Mb0orSL1b+BBQ+E2+OOe1cBp8fbhtBGIGIYb6Q6Uxv91Uc8h/ltaj3Uo9/DX7Prxmnmh7I4l/w4YYnX5nY3abs7w9qAasHC0eSzQliayVLq6jsnuAx3s08Aa0aqwQefXhiCvRe1S4BuSSogtdF/acnaH5eY8z14pN81pG0c75RkKKzEK/U7NHM0L7nOAwCuSekv5VvUgJIYmdvzh7ySr3f+pVet3qnfnc4s75ddWuoMgWyt68GVALDlebQmVMOwSI5X5Q4uJSRlWujJooRYvr+U475RW8j6rneucUK0OVI6CROEoNZ5+yDegqVyRYQm+pDO7+wbkg3eoYnjKIIbNk+5nN/RH2+gJQ2lPVEETZNQNdlzkcs4DEGdIyWBDD/u+2f9ACoZwJ9+E+HB3qmFK+8xvF869oX614BLxIEfboDuwSCJ49Gqjt9vfnC/BmVzF7PiuGH1RVscmv2z+8XGCDk7rWme5dwfQS1LcsiCFY/vfSxMe6ub83i2m6PQWnt5UlUBUcmz3P06u95PxRN2bSHOS7R8le4eb
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

