apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBl2C6WU+3sP1Vi7y/junrbezhU3L9rh61mnHgmRhZX6RgDAWVPzeKtDydcY5HQ1iTU6gwbHhajF8guuRjNWDRSKBCY50pX9Ywla4pta9Xw4rQYNcNypXCz9KW4rkTJSw8mebQ7U92eTEJo2aVYa7ZeRiCJ8Cr4ERqB71vzgDJAyaYFR97zFN85cGjFojkYH7Epx26kTne+OvoXPzzJb6dCyU285qa6k/ykHwqzr3G4Z/uno6kI1nCzupHpJwKHw8Gq9lo6sz/d+Hcidxz1q7rm9TCytCzThr1l/kcJ4D6aVO98KV0BPfhFsbHuGcOMif5H4l7j398xvwe38cJs/8cKZCxN28DYmavG8X7nWUDS+amtyqENpbrkk0CNDIYD2mz9hOrXI5baFeuO1HKwcUz+rWs4blZ3CJPXOJwYF4zfQT0xGDmYYQwUDZ2DBWGNJG06WMZbEQpjnNz4vM+YcAK0GKVK2OYFbwKIRl1xNj1lz0t1peTU+kiUvbxnG9sFBDA+KA2WnjGUFKCQekcKb6rpn9TOetH06MMXo4rMXo+2+AMoB9J/SAVx8TOqrcDF5asLuMV0+bCHVxkpbGrf91CxLF6PbFQgQUjPbhwH/SLAu/WD3K4yPdTxpzw5XwDKiRTcrw7HaSVJibdIvMjF1dAkCJMKfe11StqfmSbKAR452mVG4E5WF3g7rX0FNWvtstpVE9QyQ2IPQQsSPeF+3mmCZH/ZtB1oamg1NSpawvXQlfFgkhNry1EZ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

