apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCaIc4WeNaMppe7gcN8vUU7jgh0DA6Q/cB6YAIlItHHlB0eycDFwNudr44JEQWfUEQu5y/DpeDbkUdHrEz4nnrhDzgr7gycmPF+A/l4XIaNgM7AbewI3FW4tB1jRQkztGIF3YdafT8CyBV/LO6ZjNxqvKTKTbQlpABqVPTQmm3tk04BGHwlJYO8LfyxMgk0H3CgoFogrNlGKmlSxU/UlURWVQXhas1zavaNtuKOJx06/Cqoocp/QeCcUo1FlU7dFBgmx9UV/1K4U9cJ5dgLkF4C6FJ9bQMTEgaqn2Q7AvjZIsW5b5argP3l0qfHd+u0usTChlQgWL+kshK/KoBlU6bBKXY86Cj/r1//vx6r0DMSyj2MHAbp1EB+yoddb4Ti7QWzZkOtKsMrBiKlaTt9lIZ4+aNAQkQpA/Ji9/Vusp/mLjz1hhhXQxUZgg/GYOfm6JCHpYnT4gEYEuVxszac8fsMlbFHu6Yd1J7GSvko6ovD53AhWUwYbGq/SCO2+gqBjMGw+NwfX2hj0iifFnjTftjJ2xgvBQBNY/RkOP8fGrh9kPKwXhCy2ecrwWhH2BgS5jNKtmdqoiPtSd3GDae8+LkP/c2Ai8o95oo/dVMQkyrnZYqSBj8UXheE+TwU2kkQWoJ/ORuteIYx8Dw4bVKUbxydhlhr+9RwrNPwaI2HYsst0R5bze35vn1acArWYRcbrXk0k5fH3DMuq9SNmzQzH7reMcAvOGx3c5fFfnfON2Qr4zDS9vlzJmAO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

