apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgACv4hvYKcxVZYwaXdKjcbDtgGLGa3wWryMZ5whWfcyaSYJ1eJcBNbxHyGwOffJSKzj8roJ5l13SYFaUNMJGYR35z5KAG6LX/Ee8bDjGwPGwb/TRxVxzZyCkOgfhQtK6ZhXBVc5ik8IJtc0XSA4S+cQByl9nZjxH9OIqsmcF3S5rZKFae77HolTGsUv2IJUuvyHyadCwg1KWfWOViT/f5POH5Vf26KNX1e5jGK8zSWX5YXn06C8KUyjCD3pqAKOj4W+adt79muW1hO43nh222u4b1zD5KFgXrRjUTol1ZilX6v16jK3xhCHrgxRGGge0o3bBwpbS0OMlN7WcOTSjQpE7IRaWuqThbISwP2Vqiu5FmpCKvB/saOGHc0i0VmDLPSBDg8JXti4OkImzq4v3VpPuUZkF2fzXgcphnYMA7AS7Z54o/BVp8mC/xNg0kTIDn6cewQViVBhZlTbiq3yywOSwrdzj9f1lzIvbmok/XVvnvRfU3EEK2EA68cvLsWoPSEF8dmGMbw+RjUZ/BxeIrt4Obm+Yb2YwlGLAlrlxTnZ4PtZim6eLXKulh3gTCvSBC37L65gAfHxgQLbzMde8k1sfM4t3qtxa0R0Tb7RmBmi2mYPIXT7SCrsGts53zviMHUEoHgKp92s320OuCWGg3bJHHCSDr/yIRMGvrt0jKuzbDgeDBXp5ZqjpJuZfJat61WmTW1sUtZzzsOyeeWpSmWwidKP+DIc42i82ozHfbjzNHVSr8YQGN8+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

