apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgAWAs1U8y/73oPVoE6A6YbZn01RuTuSsZMVhyAV6R3MLjWlFWz8REpiGYRQi6gPt7W/04YHWICwoMVbHJlOGGWA28wRqo6tmVI41v/0da+oaDW3kxsIw5w2ceB5vjSWyqxJ3XE3aktyOjZyLFmslBrcVBGJglpWnisYYjy9GWA5R6SHsa2AIoTf5UWYbVXT1DicYvDJcYS4ko2Dqjktgj2W/8cSn2+oxfCNXogFAN/tGh6gBpplsBprIBk1pKEmSU3sDERfh+zkqIStr5Dk3HgXaRd7vUDNgVb2Cz4DPc2/4guTA1w98G41Dmu1A+dGTADMdstTA1ZA2bqKiquiwaog5dX+civhfK1ZH1RdFMGiZkYNJDhGaG1BWdwttQ5zsbnOOyE7sBZnVzg5VVsVvQnyKGLQlb82dp9Q9BrJh/d45hqXbzrS0W3xP3q09r5Jt41j+24jIa3N6QZkLoSIuGd0d0AVm6nBTYW7nOQ3kkB84yfv89cCWSKP4Bvjb3mxJ2vMvGWmzW+IFbFPJxEK4R7vShrTwQcGU/pkjDiEQ/0m+I/wJPXUEg7kxzSvhuEheWFtytWVMabH0xE8lJOIRI7etJfTlvkmI6hC97leRFE8m5UQ4uzouhJq/D5tSvcfp9vE30Q9JzE/xKvd18bfHShH8Irj6D7oGE+SnZYvH7arEnbfXIQ7o0F/NsMeUgAR0ACaUc/eoKxjwNU0NlzacWsPfO2QgGQeMYUtiJv1zI5EEne5NEqYWSXv
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

