apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCztbKmrfji76AsJJTs8S2ZC20c2z6BcXBtBz2LdeYelKRsuxxb5NnHyxmEAvBE8EtxDY+FnCl+mW1fqMEjTxubNf1T4hN/PDskU3xJ/5IV9F5xVBOdDXfrj8rXj+MW5j5WR2xtL/plu1JkdRNfyDcPxT5t/Ld+1092JdHA/pOaO0hQEXyIXWMRpWgOvTPnks36KRru2TXpN625WgF2oI06j4qt1ns5CwAGy7oi30SYQuVxW8ekjnGcvWx0dRJFXNZzye8SFPR18UWYzv5MRsQq7YrjOjpu8MO7yZrJc5Vc11RozdQcUWd3C6z1oUwHt5QVI+PDxTlQzo4QmSxVaXhS1PmZvAVOPUMtQ4r5LrwWOgXR9kTxOkKqp2mBCbQnlUPp6uVTRUysrwMPNeU8PGmksaLVQS3l7EtkH+N6Khw4YkDVAWWtVjU/xB5LCcAb30YUdVjwyA0gviwvXJcMirZ8hXalShkkSBMyOWC7RRW8fZIwbHyQxKzapvwo6wefNiAoFmbiKdWGutKlFg6JwmxAo8AhqOzFLE14St5Gy1rYyws2pSsNduJiG9agDaS+s+jHBqho+leW6wyhVHh7Uw0uKEUUIOBPlidPRSv/Le5pxJ5S+4WIG3/2Nr+/TVlj1TVHAre7KXE9e4kYY16tMy1a+OUVdTYfbyrouarP6Bo8VOVfD/IRrPzguRdXuNjBTy+KZXJmmDREoCLGbGjViuwQm+yqJt8wHILNCRYIEtFsDV1te6M5celF
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

