apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgANaX6pV36Fk7hPDUE6y4RH4657Mfz98aIC6Cn7trroZl+7z8qTC8W4udTUh1VhGNowc1e+mDhF0PXwAzUvm3XlNJu54p+qJiFgiZRQ/jAGX+KvLXny7jNiYjCsWEnKq7EVKfoc2MZ6BmjOZm69L1/FvyhgXodzG7LW8+zRr3beCBy6Q8ywd2drKMt12stjm/4RylJDJAneTGUghBJvjHvCgVzrVX2NdoKM5VKUn4PHc8QoyumiRUNNjkK+/Ro5PxnBAal3CLOl4tCt1JwKSByFeqnnxanYW91k/ve84qzOErFTFlRbSbZSLzCVJ2Co1/BmhY2ZHGAzqGCXspwFhsx0e3rngwKN8bH5Y/48gd1+9TuFcCvJ1NFlXu0vQ9Z+59tIexfoCNEhhd7xOQIO/I85DPExGkZVTPEknzIYG5TzmNgrxqef/pfAuqr7fJ5G12tLIpwLC85pZUE14j/KwMGxUI0TvI+8jogQ2fzQ+tGBD78UGOGZoMFNpD16Op9A0L6Hu+YpBIBdLY7KAtVz7HpEQJsDJue5xlTCyniCqYjmfvtp7z9kKWH2XWpktFlH9/268Pa26QOj9jPPa2yA6/fwj1QsPZNGswdx+Ma9QPseCzrLNy8LW1VIAaUE91BEoR9DJw522d0tC92xYqYRLehcefYFT8nAmTXTkF+pd+zz87E3y0bDZoBoQphmC88XaiEeTlF24uMS67yNCi9G5WR2NLzxJYUQ4UoLj8BN74x16l2fhSARTd9c
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

