apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCrtqW8C6A7JYQgiatkxYF43XP8y6FMtIK41FoWse8bMuUeSfX2TAPVhQIzUNtY+kaYi9Sky3XcXmtYPAXYyyFJ0ddLwwPMkXfBuBk8KOdo6tk3A9tEKP3SUeHc5zPzLGHJ8goaM/22q02AZho2X6wK1LIFa5bSHr9fQd79/X/JcJ3tG4tTmrrHcoTHm0SHzha/Tszb1DLJeCR8QDDhabFkEsSlxj5j9IZVxVpAAtR7M84fJb3HgnZSfHQtu0iCcsz+0G9rTuQuzsoGRZ2t3fxtaVw1oK/gttwDoMeVS//bUk0LClzQ1cr94qlsBdqe5NBIxDD1g0qLiu7RMuTwZFwA0UgbpMR7BXAnn8gSVo7pgFynSdg8qd1fU0/wR3/BFf5V52qj0mFSiStpjwvPVsuJHRSE77w8PenSS+F3/kuoMjvxPkC8hD62g2llhlIrh/L+q4yPdlfH5SiCT/y0vhvPSLGHzT5AKcmo3Nlx4/FEma3fKyG8gH6SygbIGMxpSjuEnyCgKp7AiQ45k0JF04Zxaha1ktIs6Y/39nLOZSL/w5A/ehTL/3CrsdMt9jTVZM5L+rg6TI2A66FkSZ/vGP+IlHOEb/Mrel/075noE7sN7foeCJ8IMRFMS8Y7WsGP0288aWU046DbZoV34aVJvpYoryZ/JRLxGMXJpnagCKz68+8OoTRdq3r3K6YC0T3LDaKTUgWd5pqFCNZ1bb/JAmOukMbSeRvsN3LWmgJYN05ex8qJ2U4OhGvP
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

