apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgB4gMP9GH+CBU8HmkBvIqOsv8FZIqYE4Lh0YJJ+yB09SnSib0KccI7PkmvwkH+MzofSAt3q5GJKW7ZwNTX/inbTMST1rHt7fMf8uXW4PiPe2JHKJ/SL2CABcIdiTYNjYOd4ra36DCPFYeucONDA191Hi9EuZocjhXE3cd4/oEO6et5p7ba1ZeQlb85navKaImhvNYL/AfCFJvHNqED2Rh9h23bPDdAVoWpYO9EH1bLQJjgimlciH2YQ95+R2icbxOABD5BhdCh/IskW7kOoFNL9y2BWm+FVKj08q2Ekt7jZY4i7GcpThFIlYTNSdzQWzp+TRddP5Wqski3ffNcwBLfcMspwA0Rj4SKBF8BgklNov6i149kqpNZUnERgIGsFqG8XP/nNdWqKhKi3qITrW5GNtT17EPb/2/cw9HdRGOCgwoEb/MNkimTR9ZY8CtEarmVqpvTIFz7PE2S9TAds8SzihzNLWYlo7ZzJ6HODlFqwBiMSNQzv604r9x1vr2vGJvL5QPBF1I9CNMMNqmUFGsjsyZTKt2n9JbAqL0fjJg+/EnGJ5NmJJwiDkoM0fCODYeI0G8jZsoniEHJHwpTbijLRu65MYDI4o1bEBcWf6DxqpBaZmj4ntkTNnvpr2dd96YPfCSNW6Mwz6yPzZ48FVCKdumiBRtO+1/3npLZAm+FrP9aZF6IuY9E8Y70X8MNZTcEsx8qSloZBSKIGZLpP+/bYywfk9ZoNS6CcLks99W+WPf83uTetek66
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

