apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBA3JSuSGRkzBZZym25oX8FAZgLZ7lfSYiMob32Vd2CmkQsgnoT2PcQvZE5QYAMrcVWKJevjQ0HcnVT+V7s3A8SPLhOzChEgACOX/W8jBqT5G/ZxwY/0YL9N1MRrGTnfj99AjktufmISQU5/PCrbVSu1Lh0MBkD9lrBEZkhucLLybnxewL41svcmODLSztLyqJXNB8QBdO6HjxGCaNz9EeRUnSeE0wLRuJM6pjl0/zJ4swELv28FW5ZTp64TzPup4OPxZ2k26B1iWbnpfeWhHPyvdUWZwWO0QI6N/x3C1OOygw9d7QmBY2GG3ffix6rii+cgvTiAUu/7VjIpxyeSMIPmJJqYisG8UNtHyFS+HxLFJM48TL8Ldh1zxhnZTYuAgzZ32VgrqSVFQkU+MWcfRwKHg3d3YCPJeMM8J+DXADb5OYYlmyzfZBqYq81prCN6JiZRqFc9CT1NMLAK1CtjQV8k2SGZ7wicXjSwJkVIOEVZegemKFnZi8bjtsKID0Z1wE9zqU69dKmr8Aw+BOSOR6D+GDlH4DDq+3ksRC+7dEsKSnlWXkkM8x60QOwh8rmOMAN3f8D3cpFNY/SqY9xw+Fo7ArbN4CvROa09a4LQO7GBO4NWOQhsNH22HrRaoDuoOoAc3FFhfERVVn2Al9M91Civ1yzu1kBhXZXFcYnyD9djDoj/AJfzOe1TpPf2EhJxR+0XIZnp7rKiXTXtCwwt/Vafh/bPp5GZe/xbqogbFozTNmF2mn41Rce
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

