apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBWnAUoIGWPbYJp166c8ZpT1C6LKFmLnlULCnSyyK10J0QPT3GDilio+cu4GP/0d1RRdwfBRbCcJN3iqGBOGXHTgR3v8dZ3rjKmZeimhZwBUeCIx4DaRcKxddELwUfvBj7FI++wkyHcF3ZeqiAXy0ObOJgTrZVwA68EE6iQNUAB2hcihicqUT4BT/ZX++SBIC/YT7p7tki+K4yNH3s+pPiHROwA18kqKBOf//Y8bp/KkW0rieSoza30WEw3hsKMEltGqZiitKuBSanb0PYWWcIT9rDuDxTkLsTilghPYSET6onAmQABR6bypX9Zy8vcVieQAHNO8aSO1DOwQUjXuUaKpw5JMLgTZJHK7QQTMpIpTz+gP4m6is6wbGc5uofR5zAnBKYxb6DIvoweH+N9B7G7kVxj+BNYgh526HxbqcjhIfNrx5HV1gJWzrC/5wp/ISy6Mk/NyJuOEwdO8nQqMzg4eCBgITHyApVmGiJ42Y2SMbKd44dy4SwkxyA1IioVX1YJt1b7arMXWXhUMU7x/U/eOlUxXfQ7K25kXJvUqFIoSa/myjxvCSzhd9XoYulY/2hR/8KGI7Uwg1worheKMfv0F7kWdwK7qFcV3fFlL1ktxZ+D5fUj+k7HlJKUeTbPINMqEWX1sJVi8e2JGXsPPk/fCG9j4VBsv/WbZIz6DX0wwmiR1iaNZN3rhiEEGlx+v/27Yd21xq/1AY6XStk7eKPNiCDeZ7N5FhTtorfE422LN5KEyTn4PO29
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

