apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgA6SM3o7a/Los+cVLQSEWOSsDeAY77W9s69S6n0fRpWFpSrKWKbq/m/A6svcDQ0UO7h6nAAHk4KxmZF1ZqcQRYorqBrswflvb0VM5PouCRondLOn/r45UN5AOTPic+5w3tFqg557juMxKoVcXjdiTaEtU2FiFQgAqaHRM+FBCmkVfLnrKjj7G11PJzC533V3IqlESgqlhJN2JF7viuS/FavN6T+7+Yp6tLovzV9S7Qf6JvEl9jf6sawhYlY5igVe2zgQLK6g8Jkpa3BXVw6ws4vviViyix8coiZgOEAzUoPpMjdBjrdED7duQvo14eqpbBAROrmCpIMgt+mCIQ9MgqBoP2CSTfhax5bGUftFHusUPg27Fv8FQyYe7F2lt7ME3La/mwanLEVSkCWWvxfin84sPPO9UYaLefnjJ6FYf2I5Ml+HZr3HkreAt9iLRmCwqTRuNV+xG5a/67Wsx/fTkbNpgJg3WjVBMAWhn4n7Xz2hZdXEnZuDEDB0pT7mhpz5JUA4dIQOg9ZczyPgBmQ/DzOCzZFudq6N719vnG2fQV0Tj5Dzc47rJYy5E53biXE4uqGh4Kz5FQQjx6KZNA9IF/PkE5P483//ClpnNeHCRWjZV4NPqRC25HQYKo0Sft+agI+vpHfZcYeq/ev44BtV0OdcXytJF/PaHGI8/5w+dlVLmDPCTCRcqDNHoLmT6mFZGAqP1FQWK6+Wk9eMQTWpkO3dabXrpyeK+r38qbGnDgyapm/O7iJo75u
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
    type: Opaque

