traefik:
  replicas: 4
  podDisruptionBudget:
    minAvailable: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - traefik
          topologyKey: kubernetes.io/hostname
        weight: 100
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  rbac:
    enabled: true
  kubernetes:
    ingressClass: traefik
    ingressEndpoint:
      useDefaultPublishedService: true
  metrics:
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  dashboard:
    enabled: true
    domain: "traefik.apps.blah.cloud"
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        kubernetes.io/ingress.class: traefik
      tls:
        - hosts:
          - traefik.apps.blah.cloud
          secretName: traefik-cert
  ssl:
    enabled: true
    enforced: true
    permanentRedirect: true
    insecureSkipVerify: true