traefik:
  rbac:
    enabled: true
  kubernetes:
    ingressClass: traefik
    ingressEndpoint:
      useDefaultPublishedService: true
  metrics:
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  dashboard:
    enabled: true
    domain: "traefik.apps.blah.cloud"
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        kubernetes.io/ingress.class: traefik
      tls:
        - hosts:
          - traefik.apps.blah.cloud
          secretName: traefik-cert
  ssl:
    enabled: true
    enforced: true
    permanentRedirect: true
    insecureSkipVerify: true
  acme:
    enabled: false
    challengeType: "dns-01"
    keyType: RSA4096
    email: mg@mylesgray.com
    onHostRule: true
    staging: true
    logging: true
    delayBeforeCheck: 0
    resolvers:
    - abby.ns.cloudflare.com
    - sid.ns.cloudflare.com
    persistence:
      storageClass: external-nfs
    dnsProvider:
      name: cloudflare
      existingSecretName: traefik-dnsprovider-config