traefik:
  replicas: 4
  podDisruptionBudget:
    minAvailable: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - traefik
        topologyKey: "kubernetes.io/hostname"
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  rbac:
    enabled: true
  kubernetes:
    ingressClass: traefik
    ingressEndpoint:
      useDefaultPublishedService: true
  metrics:
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
        interval: 30s
  dashboard:
    enabled: true
    domain: "traefik.apps.blah.cloud"
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        kubernetes.io/ingress.class: traefik
      tls:
        - hosts:
          - traefik.apps.blah.cloud
          secretName: traefik-cert
  ssl:
    enabled: true
    enforced: true
    permanentRedirect: true
    insecureSkipVerify: true