traefik:
  rbac:
    enabled: true
  kubernetes:
    ingressEndpoint:
      useDefaultPublishedService: true
  metrics:
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  dashboard:
    enabled: true
    domain: "traefik.apps.blah.cloud"
  ssl:
    enabled: true
    enforced: true
    permanentRedirect: true
    insecureSkipVerify: true
  acme:
    enabled: true
    challengeType: "dns-01"
    keyType: RSA4096
    email: mg@mylesgray.com
    onHostRule: true
    staging: true
    logging: true
    delayBeforeCheck: 0
    resolvers:
    - abby.ns.cloudflare.com
    - sid.ns.cloudflare.com
    persistence:
      storageClass: external-nfs
    dnsProvider:
      name: cloudflare
      existingSecretName: traefik-dnsprovider-config