# Default values for hub-helm-chart.
image:
  name: ghcr.io/traefik/hub-agent
  pullPolicy: Always
  pullSecrets: []
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# User token to access to hub
token: "plop"

controllerDeployment:
  # Additional deployment annotations
  annotations:
    hub.traefik.io/ingress-controller: none
  # Additional deployment labels
  labels: {}
  # Additional pods annotations
  podAnnotations: {}
  # Additional pods labels
  podLabels: {}
  args:
    - --log-level=debug

authServerDeployment:
  # Number of replicas
  replicas: 3
  # Additional deployment annotations
  annotations:
    hub.traefik.io/ingress-controller: none
  # Additional deployment labels
  labels: {}
  # Additional pods annotations
  podAnnotations: {}
  # Additional pods labels
  podLabels: {}
  args:
    - --log-level=debug

resources: {}
  # requests:
  #   cpu: "100m"
  #   memory: "50Mi"
  # limits:
  #   cpu: "300m"
  #   memory: "150Mi"
affinity: {}

nodeSelector: {}
tolerations: []

serviceAccount:
  name: ""
  # If set, an existing service account is used
  # If not set, a service account is created automatically using the fullname template
  annotations: {}

service:
  # Additional service annotations
  annotations: {}
  # Additional service labels
  labels: {}

mutatingWebhook:
  # The webhook certificate validity duration in days (100 years by default)
  certValidity: 36525

