apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgAL8lOt9aQ58eFsnoKeTC1uPMImr1jVo5hfQRKUPqnRz/wHp67UosMV6YU4T/mbuk6tQR2dFZRoLKptMq4TIgNS2DNxc3EiveDS6mleUCoIVDZW9iX293Zrz9mwW8CkIRUyqcHq9DC+4So0WgUZfyel7BvrBkGYzEnB3qIJRFMKbgG7RlsSDKQhDhkWNtwxflIW3XIYH4XFiB3RJ/bQqrTwz/pu1onSkHViGeXcE+upsXoG+PI1/asxDiUed8QiAb/zKrKLeHXloTP84u6yIQVEtVnGySKxVoRGkohvyV/ilfcHQufKHOYHrQv8illg7b5gihCX9n96Yoj5DPBx5vHUf+72QhK2/GM0Jd24rgiNtBU2I7UkX5SCMow9u/VaSiCwYlp+S6IaBLvW+rUNo0ItQ2oc1KE5YwG/gShWhtVFmZHD67afoQAIHdnHGlR62YJmt/VYyY5oeiurNPKCxbbREEW+/Vdf2dSNoVSgDWfWOi7+kItpCNgvt+D9PosZnjT/IR91/PQS/IrYkh56DohZqqr7WNQF1jrBFWwJgwzMkTpoOhzVZcX0/Vwt6Y+wDj/5SS4NAAq+T3ZALTirMzjU6WKx7uqv8hPRl1Z4R4MBotm68M/NFBuQPm1/ndZ7Ys0U6uqQgDFAKoCOETSYrkcT1SuYCaLIZgRrETWUVNlss6l8MfdBYy7ItwlYnNtMg/PKr8kg1TpzS3EmsUH2TyNgwvSjw37q7SPwLDRz5CB+YpiLoGig438D
    username: AgAzZXjhF0IzCVSxdDZO9tooKtE65F8MuQjemuTHhOhUmj0tMDl1eqytbNBNJn4dANwhJzWTgwIr5peh3PP8yv4zSi4Y1ziLzu4wzQAuuNBEPv2KVUijcfgfmBg9369s9f9lQSNh2DiMHUaSE8yvSuSwRbK3pCg/n1hhXaqc5p6kLY/312Uw2+PacBqp7YF43EUnP7996ICU7bACjx/lMc+4yZvCis/Gp46N5yEfubhkA0aLmMQfnoo9573x1SEysGFMIsshTElGfNyn8Q3v0IcdyXupmrGSdnhxWsEM/91dxD9ObrlIHQPENxdf+YGo6z3il4itScNOmAhgqYgfJBXkBHTY219sjpWbwnAMWquB9vgyAU6txujcaxNwYLdQG9a0SJ9j8DJBbryZvhIdWhkfsyX9Exa3cHdLO/QOfxg1p/DeyQ5TSJYUtUPdKhmas42m7F5eI2i2Tka6XHYAmgQW0dQfq1tumuAiF03ohhtoR5DLI7rEpvrAmS5DacTUSPv/TpVE1zsT3+NqB1Im/DqVAddaXE460QphawNxzhzKqtv+Pu7u+hDvNC8N7nPp35hXulPE5DORle4I+uorWIbVNf4NrN3u9XhY3ODDPOR7h01nbzS2wDNHXo5bqSL2MHWsuKmr2d7NS8VwqIg+YVX1a59cNdOKw+bfWJ9EAxHl97mhNoQA8ZGXu97kVHro/KQlOmsIMZ4Qb3PO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

