apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgB/FMrmtk3fxpRg3LMctImIOxIze7U9MtFE0OCmGaFQK0m7DBsV7Kp6ZXJ3Gsfak1DW8IJGUWAs3b/iKu1L4uepXOmXqaI5ZVey8nrNOgjknQmmpirJe7FSuZF258ueeF9tBtsF1HNqHoNSSYbK2kHiEYCXOQ60OaMjul/TL/EqbYnyDfdy8ac8HcxIEVotiknclo500VWgIJYzO+baL4LgYvYDf5KhfdVo610FFQawkJfPQw48daABtBF4zHQIwiTuHtv7YuSvI1NPJIrM0/sBJYQhnt43H3QdkLQavJ5iKmxVdfBJP6BBcD5yg4FoG4LcS7DeCHAvLPvHwz6fKGl5Xpv5iibM7HqJ0lsNLooq6rSDRBuV79Q5PavezfAVUk1pwPjtgCJ7T7jTMZfQHsuPBKNRo8UMmrqhU4lpLjZ4eFzO1QjilL1ynu0UbvhvbQgdTM0DplTSkjxiLzUPgTz9SXXujBhrmGsq19LlCrO0p6rIu3LipkCXmmR4GZynWNMChu/PJIv34Y8zkspzCpSlf3HluxCc4qUlOqhTtXhDoXZFHcmbIuWvHxOoO4Xsynp93gPDBKNEbZaZooeRho359iXLE4ZOaWSX6pYQU/dCDEFT4fH6Xkf1bujtrksXF/nF14fS0VuZATTIsYHvk9QH2J85Oolng3wIaTEuwHsVf2Nc/hDIB48vqFp9/n1wrB75NT/nuUokcfWk0B7snRJEH7Yn9Ge9paEwsvpX/caO9q/MDP0ceYsk
    username: AgA9EQcygHW2GHXljeOheOSH7vh9S9GwGnzQv8lcL6hpwqihD8J6MHLSHTJBuns6xzOhAMj9iN3T1beShNpBZ7wWjR/WYWJWgQ+ja7wE0WEJ6bSOLcxhQKWvP8VyHYXVUVL2eFd/pRRfep+mIVsuaWcI7Fi6G945wvnQoJ8SFWMnXL/c5NwwfvfCcOLvSrNEbUBWdrOrBOm703UQLBLeHxzAaik3Fc/u2AOnxbDf5vT4ZK4Xz9poc0nYNaAHQrdFROI4277uuCRpciIcoc/Yivu2bCCGZ7T5CI/PTWL0YMABRw4j1OuxEdR3UW5SeWqPPKGfaOnkg0uKGaicnEAt4Nk5YFupvrxseEEMzdByzubvwBtCTQRr3wqoRWJfB+3DOeBlTimsR/JJZPeX/l++TIWZI93NGwffSQ0733n9SSFJdaMRrgITqd/hKmaAG/FnOtCVXetnqi/Sh3s+eq16autNvaTsY+CGC77EC83TWCZZQX3wch7zFeeLbVR6+d66J2n0HtWkP6ASJFY+FBgS3PgozfH7j5uAmBy7UraLS61FSrY+DVPxvjx4BwvcSXys/PVtjcWedLP+/hUfJtiRK51i6i+pzmfQpl0XA3DYsz0+7rN7hZvHafRTZ3nD7mx/qBY7uW35l5Oic0KYXjpfU6e0CBK/dMNFLR0bPjyRT9pEZavXL3uUZcWevOQXVkh1irvfBql3SOiMUsgN
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

