apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgA86+GrQTXpNePMQFHVbf3CeEHapYFPEtnji243O5DXdlX69eGns9sO6n95afuX/mag7irj99dVQR1O5usg4uehRutCARrWu/5XuH55YQDGSFuU7LDtuThvQ5506SzRkiACtry4u6VbQuDSxwMlFhMnFGREQo0Z3sjr0eWkmmkJvsTSeu3VZIbDGMOkHDOyAfPlpmlFh0rAfkk/xx0U/fZU7zuNsdtyQMxY3bPmtbhQ6gm80fxiFLQwHQjy6Fjf3tzjOv2GoBUeP1eT67HzwUkedVdn89pm3RyVZUtNTGUmZwlhtKu92kmb7HGeWsCl0G9g8LbMrBRxq+n22wP3WClQJrYOUgkY593YXDxcPpRir3c1zBOIGOfhg55r2D0Vyyp12jj3WC6gL+ZUi9uruDLpeTjfRht1snsjw+NN7qP4W+tHdCDcQhs/RgF4DSsOWIAOnPQWtvrPg8hEWGPe+SM/Z6YSekIx+0IgZPPABCwB9gHLmtztqb/XzgdlO/831huq6dxZeZQc0b/o8HZJLEfYOZZt5IMzVYNRQQNCQzxNncIXSQ7dkUP4YAyRzCsWQfSHgrn1BcGrILE4oSJyENTj01LyzLLUG+Dq/oeV5Cn1d2dAkeNRM1cF5yPTlVHOOq2aanWSQuRCTf2ZzfS3sua8QjJP9U+NGi7IvagGV7xOb6sj6GJgd4JIZji83KI8O+ffHnT+Mzap2I7bRpywORtz5cHnHHZjXOoHjUvk5yfOLVEF0D18ARQW
    username: AgAz+GNqCjwNY+obbhDwY+KjbuCbklUOBKxCjVZOFonrQ8rbtXL117z3YQYNXVB78VoTWgZpvZIjfn2M+ie+d+l11ONqwM/0zQqMYDzH2n+lZaxOA7GClQe+1mRu4qzkuQDH/MCfWGyujeL/QxfcHwgVYIHPFOhEpFUCH4y+pX9na2B/fOLl+AqLbo7esPdm1KcPj6dTlY99faxWZgo+JzX38aOz+zeQS3cm6nKcCdyumFlXzaXKmlgzPSYFv0Aiq5sHcGfoescuZJFc4xtXH0/lil+TR31vdLhSTgLEHFOtzTPjvgA+2dtqR9+r0T3Ze8rSZnBkChQX3i7UzZA+Yry+biKHFVrFt8r3MOCORcZcAa3OJjgbMj8oAIdXahLEV6FpBlTUVbG6ywu7a86QmH4grpBeHiY9QCgwplqpCV464j7xuHfom9CS9DZgXMvcNClYkCo5jYP0Rzl3ZxrmlDi2ltu7RELRBDbIQmWRosXEmIxov6dPkKqkxXqjM4VgB7Mc68szFPwex4NH5AdqGPW+GK8FGJ5VIeIvJdLyHgvQAlV2MuSKLbPvikQL9ZpVpmsDTmTrzO/eKSg+4ZOWktkBZU7p7NE7ZOT58KQDx/YwxoRJoM59migQXVolQexgy4yGOWQfpLIRnZ1wcTTLWm828u0ziv5O24/C/lSIKLaX8TvVRYJ3QtcrElKVJy3eXx0RKbbqsU1CdeR2
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

