apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgBhnWYAKX+D+70CZEqnaVQimjrPak3mNBVCMB6psOgR9iXNIEKkCsRfDwlZcF6vGz7Ny1+36el13Yf/S8XwZt88La9ZiAL6wVN6cxSfruVddDXtyTB/GjM2P2wexcehYW3xmEfntbMhcPihgAAjZmx9mULUGnGc1WjpD59ZnbXNA4Mw24MhOI15AGVoZ4Tzb3D8nNK1GAxKxuRH2wR5y0LKESviMJwNE+g7Uuoek07PLWvZyf+WzP93PeQfu1WXaXszqGz3U+AxOuxLq9wD24fjhVk4xNyNOlmKN6WiGiizbUGseuRLYx1t1/SH3bDnf67A1qZuOR5M10RtHm9/tfNi9cW17zmUqDglakGB0pxEHOIlkEYd9ihHfuHkth2PpRQexS1/oIG8Y5K8Y29WyvJ8gJUzSVCgtUVbrPlvcYKylHhm0MULsNghqZ/mUe37HpCQVkKO6f+x3EfTXYAToy8MhtrL6kWlrrMONGKOlcD72evTJ9QLNbWEH7gLGYRbudHTrSyphgo/9juoglYTUXpS3vPFTqj4tbF+EoBF4+uFS29FjcEAEkcDp0195Fz/d/8gKOJyZssO5/Q5akeqnOgB19jA2uW89smH+5fis00g2lvNWrOfk0CUxONivtUCOQv4+rup4fzdtOLYuv7Dys+H1UwhN036wHHWfuKeR2p4/Tf7QLXQGlEb01Jaz/o5CtNPv674spUqIfzHh9OPVW/EDT5+BlCrPt18mEqrDYvhZFeUWHGaxgz4
    username: AgBvoknrP8er6xs6YBupE5tcncLrj6pKekMDQqxPc9AgJ9FA1Ll7j1gcGQyj2a/m+pfJ8TfH2aEHAdHjG2APiwHafFC1G8MESxkMZl47bkFKjuDoiX7AqcHSFeo4CaGgUlM1dcBsTp4DHs13lAZcA58fHdf299cyvFynKuTDaj0umcYSRm2MeaCsgV7GYpqdXYOhutIA+gIhpx/Y5YSnH0K0ojEW5/X1OzS5bq9B0UFVR17VGNSEBoL7Gew1Oobo/Hh+gJqS/aOxYQ/fganDqcKnl0K7NUYCjwso3YMY7vGsJvYpaA3SAgstaKxXmd9arrAiAmK7M/GxQg2uhr6LAZmDaeAaJPMt4SbS7U8+1NRGD+EMi8HuWSN1pKA9s6552sLPq37U4qXCwt9jGtemJjEmfFN3tKaagbiTrGazfvLXWULexfSmLcXa1vukgYZsJg2znw7Im6HUO7LCeDk6j8SAmTXtwqnEV3w8vLBeJ0DcjTJFUtV3GUyS7dm4xq7z59gAKTwPyE2oK/Ze2WUDQhJr2fkMJFv3PB3i1MWd649c1zak2kuvu8frmrWRc+5VQ2ufjviuS0e9Flxwv0AD4eJJb7Yld9xKZS3tgYdIyJgz4TbFb2SCIbgDLTs42COpljKC6/ioJ7Z2NWkeEggRlP0dP27zTErKh4B2Yf+VWQ5KE0UgdQfnBstKs8+YJ0ZIsQ4iio0bpbxxExUm
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

