apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgBT7uj9f3IOuiSK32f6X/uQtnriEkru9/HhZnt3s88qKf6E+4f3m39/B51fR4GrDgxWQHQUbY7hhZybRVlvzSgy16TnpiQS3aN8Nqxq3sUC1SolHdnbAd4eutDKJAQHlu9RGsWYq2qH0RJMMjpe3DkDmxc38IgvDfWtViACrgbmTM8TFPTeZ1x1w05F63802Dz/0ld2Gdcu3xgC7X8rpH28yAEhLZz8hmV57i89CWSdaQ36d72n7nR0D2URB4hXSaarsUT9KnzNwQI9S+kN+kALtHwUr/Cd6+lzOu5h1AgnPnbWyz3GlSAMsQlwLQuCsxbaLoGx8Z/21gedy9kTF0eMNUGeBb56wA2lBGbZJODVuPQUToJUwJcOjbGIwJNjou8r9YD18MPpw9Gh/tpshPedG/H5GjrE1epggA28RmY5j6ycoLUg+w4xew/9eZKcP2/JtHjHF8K1ECsaK3Xix4b7LG71WAqUjf/t5TIW4yazJiwfzDi940JIDMTc2DtvPZd9xdcM78D1jdYSFOneZ/wEf2RXn/ifAKTdX7S5TyG8Bc0ezetd355v17/sTYwprzl+ccVsj5KGARZ2WXohVRvOs0eBSpNKqyQ6Qp4aZLTWMiKv8Jv/ENpbjjAB739I8905jPFb6Ityi4HyvL8hZabYDHthgaDDYnB5SZ9xzxe4XSy5zvKBOPzLhuad2k4fDPER6DtQATtheliP0P5MKMRM4SPT931OBKTsJ20wpPSBVpqd0738Ne/U
    username: AgBeStd3SLpyPMk6uJTOnxFdOttfFQ8k2WfqndMML3QKSo1VrRjBZAYTLhLUcThj2DdXgCzm1VedsgfMd28vmAQI2mq1yGjT0a4EhhaoZuuaLcIz0dADz0ATSL6jMDbws9LRZwSrhLBVDJNH0+8KR7NdQtlZpF6q8Kyq8gqb+4PMXvEBJeCib4l9VIcXKf2McEDFDq6PpNWcLppNfgq7OvkoraUlWPJvUvNDO62cR4AUcNB4UICyWlMW+eXr4xUCQe3NLKmlZGN0RogX5K6SZNzvA69s5vUn9xSFtPl/dE3ZrMHjeh/EN8WEgwZS+FvunLfRdS9y+kbihVcM1R7wkP+fawfaTtpOQPhn4K2/fvgLk0bIIXtwbhgQXSt2nVuir84TsQIz8tdOdMP9QLVtdluBxApmz+IVdmt5VfE/GVGsjHmZBOG3kdl/GRJr19OV9SP3GKEocY/tLkxe4RO7lFwZcoqNjq6okgkhLXpv2omIVezfiKHdpnGSijHPH6+RUircCi2pCJuKpyWtttzQdKmW013Dkx5O6SpUNTrmRR5rogzI1zMcQuO/8S68oC17KjGC3QYZlIsy2i8E9zOMG4e/plR0ybGeWZGc0MLiCpkQAHU5HCNy3Fa2VguUi4ASecrhrAN6RLUKL1L/Qq5M8lhyIgi64rYrMfJrE/AgtWeBgfr1uC48oThUn3DWVkc/PNr2ktwb0JZ4SPsE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

