apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgBS3IwDsn61SJGs1TIUSAyLq02qbWSdgZwSjg7drjAl57Gfqs+E3r1tvTNpVdVHLW7PWy3n6UGctc2DqI7cMQdJVywBEGWQsrRgf8hF8anEOH0oycJeBv85XUmvhyloZKexvOAYLXk6wd8X5UFR2mgSFrnbv4dHjX7/BtNPG1nrAsd2tEE3SgYgkIBwH9ohdoN9L51tJDz0GILFsMUE5N36TVNJ9/7LtuLlmKkeoGUgmj3XVzbJ4A5mmUrtgR83jaeqKfTuInyxng0IUmf4/zstJfnrk1zkWtO7MMr6EPuERgcMEkGTS9hiano7rdBX9TdUix9p31tcNmcwFFPVEfjTbSr1X6QE1pSiArCx7jwJJe9lNBIIjEdRmH6sVfYFLmD2LLSDGjDhJ6GjibEepefQj75kc6c70tNxOod8aLDFcux7IVSLfQXZb6QSZUrcFxZxxGOXCuUDrr4YL5aA1GWShP3WowMA+kNFxcQP7EL9eZr9KqvBQrbGzHr+L/TRmSd7dad8Ye/6qsgbUc3cHuSIMUW/0pu8ta1s2pLwT88ZgCWeb5P0uT3kK7/ZEZh/Anp5nkVwy4Qh+rmC3x7+1/gx+xE27OS5xi2UDk4lQJT0TPLSIn+l/PkXtAYrUIoy3v8qJRS5k3ln4pz6Jl+7BCvur8i9SPTZVIYmY6vr6P822EdQLLqEoKZflbAUirwKJ6qBlpPZsSSL2zOJsRdhkgiybgCg6Dgdh7hoF2ZjHZ0HD0FeUDBbkd2K
    username: AgARkYa3Q0C2GAQL92+MQe64v2OlndwC2ZCXmh/jqsBcOHuBp3Dt+MUAe2AlkO3mw1R2hvfd5A/2xV3iMqUoFFNMprzs8oh8hvV9r/8/ZA9w3T9Rv4low7fPup5y+S0WEeZYC5yjQhaHC2JWL0l/P0Cl/TOBYtMVliH3Z/PKYnYnM6du3CKHVv5ZX1fhoRQmaRDEcTvBirqcIAZPpQsg2EMMxR/oBi+w3I7pIJJ20ITSLgumnrznNmfoPx1ihcrYdJYwStaVsBYDwxB/tRO2H/POEf55Q6U5B0ebvHRbVCmnPfVB9HhLoCnmzYnE0wnYYrBcfX3jEGTyt7vT/51MLsrDNbMubIWUClWXExRncZHl7Zp9tSzi2Mh0MJ7XPfvPFQip2hX0p4lBKqigAWeEWQ3lS3Zv7CiyI1uHbcQ8Tb0yQdMbnOaTSz0xOV8UK5eVf9wIEm7x/ghEaWp4Lr9hF1RXZvm9WYupa2ec2Y2KrlWbI6O/TwOJ2kYCg1LuCggMW0oFmw+EaBTJVvrgW1VLnrXmypZcGGxtrwb60TV776PjOmM2U5CycNt8/tb/P/zpVL8yq/Uk5dMuhNrWMIV8QcmjcKWoHtagtp2izpG/nRkjk/y3wUL65ft5ccrKIo55E22Ft/7YS+I9olxJSo8XU75rz4iCfFN3vWoBhGQJjQ6CWNOvY7bzAVpDLqD5jxVn3o2SzPYpBAVdYMSC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

