apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgBjfJBUlb5KvBNoH7jCQ3gVE2aiSKi+A2vhHXk9ZtAxgE0UftL5eCQrrhf0Xez+W73wFhBChAWkCMrW4SBEyE5mykYRc1ovB6roocl7ii5NVgK4JHg4NXgzKJOruIhuhatVuTDmsBva11HJCOIPZfN0EYxBTLtaBLxw6Q5i2dcQUv8gnljZb1xGhq4FTrhHXVHzk+rsv0ewjIi2R+HzfJHAsIchkVpFHO8fkh0sO/wEqUBtlNb9wllkbSl+TMBr7aCiGDRBVw1atFpxXjKvEcNnuSyusnxqEGQh++PKvBZ0RhJIJQxc+DzhiM1TAoPFdciIHnJoziZQqBO0Wqr8VkGjRCPUZrlhFFd55xec26TpdTD3PBs2aIlSPOeIokf42AxpMiZgfx3aZvrjLGWhdvpO+etbynksW/PLEuiZsYa/9yO6GKeD81a09ZYkgMxU0t049KazMJEUz8J4WmR4eF6B4+5N/LJpdyFGYvJBApLJIKNDLZ6UaP4jkknfw5NDc6Zkdz+NeW3AfN8zIW+RWjT5PMb7FNjYC4hbryblOHrq0LJWof76y0FMBmPwFbg0+jCX7vIcpQ4j7j8hLp5P/dJzLUWl1T0Vzq3ZYyvcBt6UU5ISwaK4XKVt/Sf5lDrOPzA7VEaSf4tqBi/6m+qFpvWOhssIOPFiolirgxeKnMd6IcthXuZeeBEAUaVUY5oqtrlBs1WRqy1ztIA5c/YphND3N/Jz9UWPxA/YaRkgr3c00gPy9vcM9sGB
    username: AgCYgi4q5DSxFYQb6EG03DHVIpiWPZpn9IVgEfP5sO24Ds1teG0tuWR3faXI2JXBvfwxkV3UNskveuRyAx2eJUUqF1epLwS8tbQ8qOa/KWeEc8ofv7w5CigI4cDx4T3aUdL38cz80En5VuszBZhSkxzRzQsSOgi7COs5Pw/mnFta/9vDw9QcXvO8MKoHfM+RaC1PXm+fQf4orh5O/nAomo/yR/vQtT1Ory21U/NfSY82SWa0+zifW4QVJ9OZNqWBcXy92vzjba9IWKkAtVvkK3Vd7UxySin0vkGOH+1D2uqwKJjFmsVfxUBtJ+6hbRRpn1XpD7cLG09/Oac4DBRBGJu2szOWvNW68EhRL0fcODV8E7tIo6z79XSF/sOvTBy0Q+9h9YmZ9oINtNAlR+AIcF66pGek2qx8QKHJ3aYsfz9ahDvyUM3+Rm2crIbqzbKYo7TzJYE/w/LbeI5Qr8nJ3HUXXfyOFWuA2ELueeRGsP4taBHpLZ9Y00SLNCf0bW1E6yh9IJ9pJnoWhAifbiCmlKIcyRFtsdTap++9Zm3QRTaTi2zU+jrooTG024Frud4Yxp2k1GKl3liR1KLqHlVgL8Kb97dJLfU2mfkF4TUpUwnbHkjIYq947RMieYPSpS7HgvQ1snflakMoFS3PPdKtVsuMZYcnXgGUPMyAO/2LgDMwNnqf8gNZi+ETpAe0Ngc1yydHh2CpnB6LuISv
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

