apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgBHcj33kH/RnogHCCW8qvjjWavlWl56jiwqFupcTJ19MLBfWznlrs9AH0QgndKIPBefSQj0c5+TEbfg1Uw7YxWrtrtz89JrHqldTvLopjwxMeo0HBq0liP0sBNJsv3plW2lBEL3awmowLW1DJLf0PfHyRqGi515XifKCCKi/f3vfI180RF2SGasF9vVF0y1nHRrN2/9SPWEv1mxj1g2HHEIMBItEujVCg+QDlWUStnbrZ14gbMeNP0aymghSmX7nz8puzJ0QlEPQVUhHP/bw74SpiniyrkBe1vyLIS/6pLQbDy1Ljk+7WmhCYY7zrDjlo0BfByHH/Cow/Qa6AHljo3BNPP5xAGBSL/8cVK3QC72VQuXHGPGaiOLEDjw4HXMZECdLlhWIPWN0hXGaF2GAOcqJorLlVpK98eMNWcP2S2+KX9cYZQbJnG3aWPABZDEYkU79Tbjf/I+mrL/Bpyd8ng7JBN73F95Ygb2hapbtulYf9gXrqXz2q5vz9sritLCaMrArbQXLsXv4/WFFqMHqx9i4UVMZNAkA+mfBjDuP3Mx3JrcPr4W/Fl7yH4K7pO5PrZIQEtW7RbOO7AZgwr33vPe44ijDGrORmcvKPUeAIZkg9ORSDZtJD9M9LviAljt3HjRBAdc6cXCnHV+ke2bxijt4wx7bQFvyIcFzqPoyf8Pd+FU4rJ8kZNeXN1GcfAKaoMYZh/sxIzbYcPRcOKIxoCHYgaZxUghk7yrKlIBTOW41DBderRBeN8Y
    username: AgBY5j82J2EOf64JWAl86BFfuzRF7KWfkA/B20oVIJVp3nKLWb8kv7YU8scygxet+dEHpVaGlbP0vTc4TBGLwdtMG7b+Tu/NzgJedzQ//iJATlkdKIyuivSyvUuaUxoEyCKS7KA7fc7Jw+Qd8NHId3tvPAy1cXTkfKLD0LdoLvTkKNDJZrdr0wRKNpVxdgMiMUiv8zhQntpS/WjP7HVzeHDoxJ5Q7FU0aVW24EGsBEjgmYsX2GL0r75W9Qm1FnYsZMYqcr9o91CRj4uQ1XBpfUOWMNdtLMaRplJ6iUn5R5SCdEZEQ0f5hjE4LqpGmMzCouuJSpmsHVK2UgbSPvww9RI/W9/p578z/92g5CqXYJVrsAeKfh2Mk5gHwNd6Zicf+SvafLi0RwqI4nqn0W9GAQtxib+1ePsnbFSr5wL6P1Qh+IZasstDC4Vc8ZOr2HLVqGkFp6dkmYzBlxiAKCg6O6gmCkU7xdtWkZFVGQ4kaN1CLIMh47hWGq1YHgaLYZ/lcAHnvLZEsWlgid+3kcu+cMwSeycrUllK9VN9r8zm1vqFuWoaxN0mTseEL2ZQA1PvSklnxTnnnS8DrF9aOHCcwcAjUYIXR9Bj66J5KJRwmIjvQu4GMPcL+r/Wan2GbPkPXRRetIGG5QSlOWXalg/PS2mXzWSO79/y52x1y6lPia0N2m8iuehECPU6Aku/UxmRIoxSN/ky9J8EwtGu
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

