apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgCLZPnPBtAQi/y1RNcclM3YOQG0nJylsaEYvVrw7MxUcp3kgrOqDta9RX5FLI1DHS/CxaRFID6+L2g9BI0Aetqlada5MrPpiNynNpaunnGWs3k+/rgovxzoJdV0ZZgHMBpiHXhYJvugIMJ/AsI5nPxSWhALFKgIuXJbZso2LSDvJjPlYUUyEUJE9emW1WPO3RiMtbqb45aFcZtHMSMmlhnY53Sf5Px7chwXuxLEb1E283OpMQklg0UgUTigk8nngXaSGhpGz0I/8b3tvM1aX0N9OVG04yxbcpC6obdTepwms383M1N6J5v45L6BAMj8OPB5BNDNq5jPBjALjepPoe7pmELSLOgdHwVQBh8MiHQPdpISw37CXz2cVLV+RVYnfa1XeIJ0C/Ll4nxQR4Ce/RfTk6COzn1XXXsoP734qx6Zjm3hJ5tiaxL/9wYTDsWdh2MHEp+DdSD1femkAESxRCJ+2km2DUza1KbaySBEIrSAY/IHJyONQxxojeUJFE/qDhEBdfP4u+OIZ/qiFgTW07NX+N3JL+saE/JKbAZ3Bdqg/iXSUR/8Gi0VLYnEp0MfjZLeAj8IqMFrzZnxMwdgJuDxGBpsSwfao4fhUClbCltqxdqE9OoaTMUL/BI4WbDE2e3bix9BciEWxbUy1FmBLe2yu5Zt3jCJ1UF8rpFoeJuNs5HklIki2Jw8K8lpzBauL8XUDEqNOx8PiJot54qjBSbwIUuDC/RYp4flkisrGCzGbS+MbKuX1nhQ
    username: AgAZlRVcuaQWAsU2sniiNzSDKo+Xdp9CwwUADuYoF7koi4V+uTp3SWidUwhrmFeZVFHK3q0qkjsj0KkuDq45OnakaworF24ej//I0oQr8Lh/+5El9IzJJuqLvs0zs3KbwfemPEtavrmQJzKTHzx7gScsV6B7aYxHcaAfWvP6G61Y+HIw0EwSQ00u0Xpr5p6ZnpEtfBNygfsqxex25d2seqqGNIdSZJzNUWeTiMBwCGjvarDiOviYt+xhnp3/6FqS0ZknMYL4869FYMpcP12nMPi0lqUNDUV1kKHnrvm1bmm4v0hXS+mcR1GTfje+S9jr4K2XZwuitoTqCQgOH4XLdGyQnaSbkvLyURWUp38fMAy+Uk599J3o0gW6Y0J7qlwmDZVvT41+Bn3SWaVz5d2wtssLQ6pG93SG+gzhUyjznlUoinU5T14ANQ2JA9asiKawzQhsEHsueZ0r91CFy+DmU/OGn4jn3R5NVLwa0y7x+8i19H9MNnlPKWlIIxFUkHzMcWxzbcMy9OKL4wfq5CBhCb8tPhL6tcqbLWAQ3N5ZHQv9Q94Pfh0IuCW0MbkF8/C6im/4/fVfWYOEuHNmGxy2OYmHpOwdV4CNTAlosYwemn12m7pQq954tVlObT3XfPY4FVMEldbK8sVBVbYbt5oQ5ATI/uIbOmqoTyZrjzK4hUzyYblLyIZ1XwkSew4KGyIzfp/VEp8XQ1EdDNBr
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

