apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgCS/m3Zi9atVl/0iJntp+9dgYeTA85Re4RjhqoOXsL7KmP/RMGXfMnXJo5dvHwFB03JpEdpOG+Cfhlf9jtUK1yWFLAKQcygjpjIwI0yzFVoMLD9zvvlt6a3uaTkqrCJYAcMEiq9YtM2jyEYL5jiRSFaQWTcV8BUKqh7p5y+fYkJiooHDD3ZilGTp//Xd+GiiiDZxL9B8UfXSN8DfazNVwlERh3bTBP7SNtIYxgaFHz+4d/fO52YOQsAfdZ21GymRc71AKIEw+I5d6bF+pNlrX6NzWzX2xQnAzcO1fnn81X5zZV2Ha7hOZ8xKGR6pNkeXq5x/RpB9mwBJqlMLxtQVoQBkJwY+VtNloaa1XpuXSXnHpPGkpwR91qPHABem33ptQOnQBYL/TRpC7NPxXbiAfhtU5EkSTVePHssMuDkyHfO/RzRMkaZx5WNjTwbLFGu98Uz0J3oVxPDiX+E8o0rm3XgjaL5gzS5XPRo+njK1dwwKL0CyqPw9HR4HdU+v3DBT6YEJy6yFKTE/8RkSQp6ssE04xCpVGXjjYtekhArBQwEtHR+TXLjMvo437AHJjlvFmWqVihGP8pApBbSnzhX6AbaBbshNzsRkAT3/FEVPImEfK57dD+w0DTZnEOAseZSj5iEmU0f0yMsmdC1Z1OqhVsp/xFNlgSxRmMUtnWWHNZ+tKhNdrgb/GTHwxJFbwlvGyxG+ao318zry771mZ4wbTwUtY8Fa4CEfQazX23sNizvaMCyMmazwEes
    username: AgBs1wVZpytj6ZO77P1afN/aj77YecyUQm2Nx0hOasGI/KPrzEeH525mP6hN2aOeQNclyPNjR1L3q2jAEFgpRfwvFOJd/xAxvAZkFQMWTBYk+hOc3rgryd2zBAImtS7C/yjrWicqLBVpe4/Hsete7pC/BWmT7RQc1qRpi/OvkVoUn54nqCO1X3YOsPJxVwhQTZ95OfVUpr6VXc5wvcLKmvzMyJV3m6dqltiG9M6xyEuVqVj/w2Id8LMfQkimU0ZBy9e7DhwShuXfOg10yFUw151RiO9iVpX+BfOn7P95wNbW+arm07j0VHro/feSnJiuTgEhSA6q7OzzuSHOZkGypr4tHyCAk3hm4tUJBxYvY5AIx5rkm6bW6Yktkifon+yivD4owZXrfHTZnr+lgYGbxq6AjHGz/9I29P+JvSa3ReIXok0IvFWirD0VhvkPMkx9DDTo0M5KyhkeA2dDv/3lrEYWMZ/d/rKrNRzrY4j0vMqLVL6wM3Pl3Xbsjveb51JaM8FxQp2wPdS6/GUGLhf6efq2a9aNUOlBfGlMW/0isXCDg+mEk2sHy0Y8UIRS4r5xFxzqVg2Uhn1F1WlZjlpB+td/0OK2qP1Ptawc+EaemFJh/6hVbxT1b8/rVLBrgw4p2F+xm9oLwL/yF8VuVizc1hR2GusNzAh/8lQj6W2xyn8EF0pvh7LIxbfC7dVVTl1edcpdSJ6EDTgxafxW
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

