apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgAyd63L49BLwz0ubm5bh8nu1ePBzI+JRgZP+ADK7fQC5jGWSpTA/523iyUJUaIzdP0YsU34hThP2fx6KwcOykTJM3/XTCMQt6R56/OUjGxZnwP8xzQK7NG6fHUQJBdpsQWn/5WDjXmxMv2h6EHxAmrS5uq+qd4f0COLyc2o4msED0nuTialOT1HfO5FJjfSSQROh7YChsExoROpEnNMIEeadnY7OaueaSr2i9nmL8KXnipi8pkjMv25XaTro4hOQcCO+DxSxGcFz/thCASptusnCDagDzw6uq6AEJY0SE0mkEeEPa6INbNQjVH8OwPDgUWoq0bgG+GXqPImmvTNEwPUcG9uQquBDWhYWx0zGyiFhMeVTGwaq3fkJla8XpUhSqlncAee/aeWJ7LK3vkqqBkAu+yjBSX2+sTP0e48UkZCOHO2Vxo+wasHQQMT2EeR0LMTeNro570qBFMtGBanSVyYvaLSLmdJHVVe+acYOK5yQvj57U0jrI4A2+65nVkhFvFyNrWFIE3nDyn6OQL5k/JVe8RGlvVtOQ8Z3PFmIu5fqe9N88CR9ectwKbucLz190HxMGQ4afPuwr2ywZucpGyT/MWAR88RKN3U/bTKKPFFrEzJ0t6gpkPCU3ljCk7cIQUlpWmK0jjbicWKcp/Kyw9y31OYXWtXYaFBlQG6FERaV8+xDGtC/izLFAJw+GrMkRUoNpqT2Jqp8QKysDLE1jHMWcdYpJ9Rik+HiIlr7rZqxcIB9ok0+d6z
    username: AgCmUt+jR0zcnAHGz+440U8ADLODb8aAePsN9NzbVZuHN3Lx79H7UJxx/kaPz+1u3LVKVOi3moYzzY67ZDm8jcyb+5BBsrtLl0eEJR7sVvfqoegH7OuTD0lcItNXqOaMAi1AnoJbJmFyDJMxkCzE3bB3PGZKyXXKl5Xamcg3FrDFcFxCvHHovB1fJT2D7dqr2gDY4ZVSgI7YFwnWJOBJ7p/4TdB4iBGsiefWsjVppTFdDDwQQzuSE27p0N2jwrfGpn5TR4oOQcn9lNEqEm+SEz7FGoEFdi9pAI/PavFQTcSPHwM+oSPw06SXQGS8dU3+OjyIiUAyjCf6noYtCknqstu4skJEM28dMDuE6OLheaxd8znl4m6n8ApUs+jcQ+HGSl/rAng7/geHRmWIn5rY46Gpc3fNwis8uMr2vFBe1s1OKtvYlcFFXvytKa9g7pm5eFCxDZI43Rnk++lQ8sTvH0UZ80Z6qzpr+7RztUxfl7rq2SOxWJKEahKLEJoOXE5ekuWilX4jp8S0D6knh/P26gZwDJsPtzFSqaoFxbJB3zXSbq6Ng24ESvsULXxgC5DFNg4jLZDu+IE0m+XZUM3xbwbysc59UWU15NUJg617CO+PSatbsn+m756lOvKjmSMqiSwjjjystmfEDru2isjZjFxB1+r4QKL4ixHrIoi5sift53ymRJym4aFTB20NDfA0OvnvczbzyVhYdL4b
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

