apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgCaxzn+yk593PQ6BUzd0pWAU8V5pcla8ZpSQMTWCWw01vNMC/rzfc7Sv9AcUytopHEeTChtPUuExztdvSSB53sHc0HDvVG7umWo6lWe0BntGAUJQUjCXsbOfaJSo5agBxM23iaOR87uqKO5CR3LLlD0cJgiGqaOl20Iak2rKNYbXxsurqwtI5kXxLRCtz0eRR9zpSeX0dl9YWe9OcWjXnCuBETG/4CjIwpiNY4t2s9ngJ3t9aWIqedsOThaV5qr5VIb5wnSGw0AYeoehreWhtr/H3sHVbUL4PozrC4WG/8fBYIOxRp/U5hEAgNiNIpg1cB+A4QilfyUU0HCMz2Vaw8VyHcyHlgj/8S+GsacfULg38bsdfgw8w7OYAZ5nS7BDHdASRQ7PCqwRrRGQv0qJ6FnnDs0pdpfKVP0Zva/4wPUa076HdyB7zmZC25KIWEHjB15eDPrRzHsM5iBFsLugsvrDYjDS9OPavkzV5XBvcO0cSNtOfmyvWj1d8f/kwT04xLEdUen1IQCLntb/E/mc2jYdsoPWsySJAn7b3vks3Ote9ZOk88YiEAxXgp9hEvYAUwiWM065jNFAeKJ08ZNMldkaWLJHyvUf+P9xGGD5OuigIqLfcmifIZm0l1TMabhLGiO4c3udgsGLFGLBunPmIRTMwCLZQBxaHhJ8FiIgb9Pg5+FUu7VF76uI98D7MCaxoHYoLgjd4z2SfhwhpKuf3OCszyKpoHtGkKrYldaVrkfJnH1ncpisVQo
    username: AgAMguZN0F4lpy8o/g1Ee6Lkl2KRVcZwesW9et5wMvvISxUZvLkqjv2TQT9iMzRzUvbCE1N3J6QTMnFIp7M9zOh6d1CLLGp625L5Imnj1sqmDcaDmPVWR5ls1rh+4Kti02cnXZrdI0i9DRLPWAdAaf0EJQqQJae9qXOcVSgqkCTSQFAD8W01BxR81pUihpQSCmitfk+C0m0gCvP+/dvh5TEQQmyaNC7z/7ppm8/lyhGWJSdNw5QUUbwlMDghYNDiAUwPSf8cwKufsR95Qy4HH4IPuK+B0j3HtDTQ2Dp69PoVPGSJsdPHXARLxJ81YypjzHdqoqRbGv8yXsqKLTkUxCCiz6gflGu0pQnb1lhF2FiXHt84OJRwB2tRaWBxE2grjHYx6C8MNv3yx6ug7AJXFS1rku20lnP4lkwUOfpSETzle063HklJRFJ2vzcyEyoDRmWnR9Nad5TbdRS4Qb0cN0uvrIhMpfkiu57JKF9LYAYrrv2mBfQVCyKD2tTgzbD+Q7PDKFZDpXdA1h/ZMGnbe15Xj+DuDTQQK0NQuyABXqLlOnan8PG3gdmcWpg853owrF1H29umgGFXB85owE9HXpEJzyke8cro/LYjOaU/QBh04tTslCr1Q+thjU2+psle0XaHAu30SUFObCxRA2vIqLSiWTEWYpGvaqeC9+mfl/rqKHDNiX7QA4tLuNGNsH2dIQ/fAT+7sz4aDKoT
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

