apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgBp3vdDxDmw+714NOAmB8PVosTEpL0WH5rVgkmRxS0qWB6k99huwZDQO7qIxWBQjJRt2pxQHooglUmex/zlGJms8I9tY+Ot1trPGQpu6Rut98uQSB+HLhp+MaxsEvn4E8FsGSazWCkG9UL3DQ4X/lf6jl8S3KTipz9guAv7kiu29aIAe0Lu0+ece0sxBzORqZB0hD4VrOzHesgItCS6NYrCdsUvWXSuLOaOMepXjACdfboazY3OE2Sg87xA80/BeWx15Au2WFjlWtcNNQgYPrVBpRCxapWVk7HfmbxaTSgWtpgJ1dJ9WOUG+r0bBQolXf7hCobUzG6qGg+9sI/QDHrZVdDUkuxhLwrKX6/oiGTRglzgvFj0LnI/qvnd/Z3OTnzcs0NKDgZsntGzGCh+nVdKyqszQOWlc26o+qGXeaw1fx887fshZiHrpVgSVDStlfzEi6OY/VdVBEEEbp1H43sY8TQyUJp6ubqEgjTaT6sQg8zlfEjpAw92nko5MJ+//9L6mCWhOWZpFnlQiR33EwWmJerHMSaMp+IztrbvYx1aPJqGqbJ6r5E9S0xEp9clk8A44/7lqys/VuSy1ijSYy8CB2rj4BGE8AILAtUIR782XojNfEJtHX30sxmBh1OZocChk41HhLpd4FLdaUECVTqORnZSQqjhAnusM/cjULqf9rkXxHu2isNm+P0QnBJ1bayQmvJ/GLftFGYhTKECqhpeQgUtDsUeknbMnp+X4iBBSQa3jDMaY7FA
    username: AgAzFk8V64hsg2evQG/82lKWI4WUQZNqoiZhISeIl9ZRrDRs4DwqEW3pp1kzgbG9uZXORpdq/bpzg4Hco9LYEKdXy/Lxs8qvDm9tiIVh6nVD7dxpRtL+1LFQflkvuNJcw3yu4j2SeDGH/n2ZC1LZemfIXmwo/lQs0d1N7nk7sJ74dBxHq2tQhDneM21JTKnWYkILVCd7fW5RQd/OoS2ttkfq7viiuC1FP1EBb8VD1y8Csjqqgr86WQN81e0GNRVn6IESQMzj3GVJoKOTTNtBHcIi0xTKWu60qDgB4OkgQSqisQ995/fVGSCFo9XJZvYGxtOhLolLZmT7XUnh1iPP7FFzsY6Oe3/k/xZBrrKFm3RW7IoE/3xrUddBRgqgwerlMnR8nGI4pADIwbWFBXrzP7dkCxFQFKLukLKN93PLIw/69owVyyTLPbuSLfC9TROialZXSINVoFELtY3KW0T4PR3Im+6BEfGljaOUw2fQVKyV+AGggxNrs+aRhIhan8RbFXCoNWWHa+Hkn481uqSGZqSicr/4xgvxW8sjk6Sc3UcMALW+mm74qFkZC18LmMm8DRfqjADXGHhCoNY7mk3rYSqFLqXD01ixOmf3Meriihf2ENDoE27ZpMuAhmMBIoFCkKsHT+NqQ8ALfcKwzDu3Bb0wpY68WNCGhjEhzBj36eSwKrg7YiHqSq1l32+Vt2yxswjFOOnEu+95BQVk
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

