apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgBNtpPEAYPw0GksbA+OaBbbgs3U1xUIZ9M7e4YUAU9s31zBVnvY1rNXQbLz6xPeW97/8g8EWEvaLiZ8GyCR+4pWsB5OlRgZ5jFoygCjfoJqWi4qknY0SxD+/c9l3Mr74+deuhjthcMkHfIyAqFJJGhixvSZhLu0b9OblHLEM0eYZD3gLy9CBU7kSokZLRl5Af0uVIXzVRoK456wmLvykMztQj9fYxY6aYF8jzHHCaxfLBnvFAcG7i7NHgs1pNbqRiM96i4Eq0l1+VsIAe/nCTi7S8lGtE8dHFXN5h6tiYfCGFU6dWsRjBM7gUY5AedrKjNuEMVppvN4C0OsVSSFxcjc1lwG/NpDnHDzf9HxuE4WgJyHG2jW915Zkxc8hWO9ETtVdskF9w3RFg9S0/IAvcK6ZHJzJRycfjziFrxxQ3laiqSEgrdXv0/D8gTnAGgFpimhJitmfP+6gol08MoUNZoQHD79ZGbBUlaI8d+Twf3upLSDqMGUE7hUiSXI8lmpD0h2EeuZxk2QodXoxAWHU3fyMYd6uOkgHzld4zr+zhTyBejEl4lAfzoKVcgEutR/wgKubiAV1Iagfl5bOUZ+CNGnZghiRfEbFMfjcR3/csB1iidytNHIO/0IoHjBJaVy9u04+Jd0e7Cw5r2KCOEXIzNxUj1Nc797qY7Bqoms6+aC8jcV6BRjlna+GeLo/fRpNYNTx4afyJXC5XPSfeN9ysiVQK0cNZsPaORAfnH07ctGX2sPXN96mAZu
    username: AgCU/dn8R96iINIKFrVeGmSI7RngQTn6j4FZ2vMSLpnb6W6bafV99lgbYlJRDuDn3VmiTVk1Of42S9EQfH3CbIHSYeipmTPcTjl9PW67NDgKKhAZGNnVOILg1zX5DiXDH7oaNJOyayY29tYyNHhJD/zb3COIvVqhCSbuhtepYGhy+ce5fUTjK7Dvvxllk+fn6uh9A6Qh112ptMhS5PVElxqWQKVp059d2k8c+mqySnJDPOwr8498DPGUcH4a4UeRoO8Q3sCT2MygQIKChRw+VXMuzllgIqWDvNPCAz5MojbuWZkTXAZ8MfRfqCQpsp7GqUbt0MxkjuMzTTNP4V7aOQRvOihuMX43WOYvMGYQqwyHCrJVaGY+LzwpwUKG1lCYPmh9/P4qexxR3oqAJZOdmdgR2k+bevL6FIJoTid2S4X7rD7gU+Wv+BwL+P8ECQAMxmBbYmF3yggyJlqriNCIr3CWgSwpI3J2kDqe8V+getqlNSDHbw9qUpVirD2m3anpe2w4wOhb8GO5e0zKsiX/pr9lZYZyELtmvOAtNE2WM3xfvH4NmGgWmn5Q9T0kVyfnyEwKqs3T2EZMUb9XitcxituuCXKWiv39XWgKnFFOrl8kq3IwPz3EzRkPBYNr85l6mOmudgjCczlvf8bFxDw7ppMyd6NBgZ9MzmhcEPBLqfCblpMjafBKrWHvxrSc6Z+ZqPcIuT7Tok1FpPE5
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

