apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgCe+lJhVPytz+Kw46ZRRlF9cIPPYkwyU5oryGVGzYPzo17clinbZAz/OkGZsU0ekMX6TjqCmYcJ51cklbgGS876C0hErvMWAI18eWzmEkG0R6+yx5VBXCsk9ShKpHxL7FYf6JMYkl1PQQjesm/2PmvfTa1tHorI5vP74esQ0FV7QLJXj3bZuS9x76chuO6mxiiL7O1LuNqzNYqa6CKpHUByFapz9XVE9b7tT3ERvT7l3KBpNzpSYc0IXYuVma1GgIFhCjVJwqycf12qH84hhz5eKzodK22k011QhkRPQpO0EPVlMUOsUsK2s4k1ionfMghLUSbZ6afP1WZIYcuKjzqAvsJPDjPBlWEUMCDmxcaWcYlZhIddUKtf7d6cBGD4nGZyNa6TEv6hC5OeJtIagaXoR3hu/1r7gOD8kuyaF6XTxGj236n3jChQSPvWaEXge4W7zY+Dkxn00lp+HwT3hONXR0Iw2zS92nXBmh4yur1tNZwhj/o4AE4400lri/LYNzQBj6H9tC2feAO1KKxN+7huzLknY1byEoi4Aec/87lVC63aBrsto6bDjrd2GJ2FJ2CIKAuGIy0B8VGCXXQ7KPKYu3WJpcWhupShd5rZ7QcJcYkE61qwGXAHHCZTYvif6GJLz21T0pLl2rvF2Tv2xAc0obOFlGKjZ3NK1+v27cGZoJkduvoUqlEk3VzXR5mxd/Z+gEa9E9fDiJWg89lY1fcdS7DHhBPrlcg681agCDfPFKPJ6UAKIfNS
    username: AgAhaoOxDVj/f8vzhQIxMJNyrUDS+H5mpiAfMrchLmsiU2r6/LpPBrTXD5I85XQe7I0PUt6jRM7Vtf0w+ed0uhsqQf3zoSht59RlvtV5E4sS9USXCJUPFV0AUORT+dkyuTHDG8/mgMlODB/UCvaGNtXYDTDHk066LYNkmrIkpPA8C9Wj45UeVeMj57m6LcqL3JuD8qdIV2khzYq376N+scBd4lEdckI0i6mxiNBaPJLiQ9Jsg0vMnMoXoelQShIoWWin8LOeUquK8x0mmH06JJQrs/OW9HzDKvb+NEbHy0npzcOguztgGK22gF3+eSL52N2VzqYOeayCc6ROaWLn0BGpawnzIm+xjMcKuIiaytCONQwlvHMm1BZs4LftGQTOJmjpY3ux+8pS60DNX2sBBz4vcDSkAmrTP81E5B1dnq354yCOrSMxEmp0QlKphmK1QtedP1JvBHetmTPHdtbNkFjd9dbgBbb3+dV9xOTF3YXbQSKpUZr2DEL4D1HKsqFoj3yG32ce2imVP42gmVi3Arxf6HOQklLcsBKXEWhoPjOYh/Fi3QJnfhZKGY+leHVqPPdOmSWrFo1xDq74ZiprlY4EwK2kyRL0j8G4n4Ron3R9qT584HBGGrat+mUtpnWzKG41N95U7G5ob43BKidk/ZbN35dTD3FMQJuFFYE26/fNjJjP5+7WfUJoLUlVlcQdYtdDG0p0V6il+7Hu
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: argocd
    type: Opaque

