apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-creds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: manifests/registry-creds
    directory:
      recurse: true
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: registry-creds-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true