apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: storage-configuration
  namespace: minio-blahcloud
spec:
  encryptedData:
    config.env: AgANx574P327vrdVi+0BLG9I5tNSki+eo58f9MUWag9r+Qr0BsVZiJczfbYQ5+JAbZjf5TI/hrP29ASqrx4JfFrbriJt8l5PS/F9ehCxDXPUa0UlWeRqhJCyUp/qX2Xwh9aJ0T9OxWni58+3uwPBX8gbe00kBmnzV3J4cAdha9CQh8i9GUhfmJve1xJh7FcQZ7ifCTJ8ye7ko2UDByKPmZ5KcWl1ELiVVgl0vS+xPb/7Z+AtiiSdPn4gqpDZNEUZH6aqaU0JbCvbujBGSvDrb/rhj8obkAPxIXMe89Pirerf9NOqb9pnf+8pjaFh/6EbNYKrgbHmc8fkGtujl4dKTQ6TBGhBN+sPCDViq9DxBcOw/bcfPK6WFwHBjh1r29Pwccl/pg3kHGh+jNehbA2QE8aVkTZEi0Ope/mK4PcGv/rfLlpbOkqwmQzgc4KiJu4zA+zjhKXvJnxc5oxr4NtTxOC8zqiHrF1AEEsgseF5Qau6ySBQrKucPs0K2vMV3tR4+h3jfdvwxkmmcWEFdPJ04r0paonBOxUPgJuXaZIiRYg0e2WeXnW9BwUDTxa2Z639W77Pq/PWUTndTtt8kojdNxV++qgLhTKbG8W58/QSnCRFH0TUCykIluGbYcLSsi5Vl7Bg22qP6wUNk29U4NDbHl9t1PnyaCRjusqueaC/o+igaPy1QGWqta5gTbD+79CoZnzihrDvv9YJ4Bq1AaB2wlpl0fjnUVaZ3ZirvYZySNIH5kALzDq3dJIMKItAB4VPCcJLsHkv0OTLUncP71j7JJpiRKAL8zpbJahYdmKzLgN4H9//1Vn1ui9ZX5Bh5nQYgMOPxeD9xNtiNC+t3KOfTHDC76SvCH3/DdSJEqIXbV1Uu6v2Z9/03yfCo1cLhYaxhh26gi1T+htHq6eqoBwAiX7d1vtXNiB5JNH3RN55doKuRI9k8F2YP0l9O/tnduXsuElSqkB7zQNbbm40VSNz+2r03qHXLDPTrqlluSya/WPLQIx3gp6mOufG5F1CEoDvqWttQj2pxzrK9C8OFC6Wltxs6cSOoYw491qGhzO84tHil6BKR52Uw4wz2Hr7S7hYqESgWwBEYw0c4Yz3AhIWjEhToRJNQBTnmBkiI2sRhqbS2G/gMAoE1lrvwXMuqdJefD1UY+YlsLQ85F5mBLmk6gHiEIASRDw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: storage-configuration
      namespace: minio-blahcloud
    type: Opaque

