apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: storage-creds-secret
  namespace: minio-blahcloud
spec:
  encryptedData:
    accesskey: AgC7m8vO73PZLftHdGbIdb/Wq0rZndN+uXdIUN6/tUti69URccRm9M6dASVDIGlcOu7WODsounZ9ugbbSQtltarVKgpQN205ebwdsS8pmh1S1Rii/Oa84kQW+41lVAJAJN4XRa1CDuSGcGHP7onYMbXoMQtpSowytmFbRXqzwZS4HpE/DO9Z51/NqDW8QvRpB9WZdIQhZh9Wzl30ps28JajBaKn8DBjRHZZHgPcf+T+cZQBWbtKEKuX3ZCuQEECnmFRCe1EV3wUZnOZhJvfK8FzJY3oMfXoP2IYx8lHT2hlsn5bDYtvlOTMqoKpGjUSwO6VfaQmIS3YF97DkH8c4iSO6JYfZvRRVEPALICArhmO2+aid+yeNuyA3seC00M9rZPtY31saqxz90BPwXutzX+qVTnZRXT+d+kLFeHTYRovtiNJsrQsqw5YZ7ltU9WqKiJbOdCXROeXjt6nnZzbHQm7ZGztmx+sjmHLfYt+CTI4BxAQHFDjeP7kNILoAyxNvGe71MoetEM9j1FbXQI+5x6ADeRCkHSC02v76CGKfAewb8RPs2WFPjR04Ud5K95sbOeA1WuTn2rlNvj93Vu3M9asBpBuEiDqS16vqiDU2dkCUWV8k4YSpZ2w/uHUL7A2IDe65j9VBdDYR0ORBcwZaOMIVawvwi5Ja0sf+WK9jjt20jBq5X9tjWEAWHR1DEokopbL5eQF0FCu0LIHsErw/s+4dB+J2mg==
    secretkey: AgCKDhXpMQUl4vhqFvay4eKf5kpDsacoSUvo3nq4u7aC0Fg3003nbHuKRwzTfGXmGgyyO1HsYhSqPTN0Ftl/fApqjcXDZtAksCLTzY6BCo6mGOx8SPEYQ9097boyGaf/+SUVN0aTUshZSJrCe0QeKdaSzzI1zXZpI87igWa+Z10DO1p2EMu1erfYMxYfQ9b8bqWq1t3JCcMAv9Xo0OQ55ed/xcs6nQKY3jscQstU9Ab9WMPE+i22AzADTE/dgvdV8fDKtzhG4uR9DLYyaWq9hO83eB4R5dAgVfraYDz9N8xNrODPFSRNsmM/PfZg4/JPUDYSBWV03g4Z7y+SvJrLKTIGGLMUIcLtMBKDUCUIelermVTHzZI1zHNjoWZ4R08b8L+QrV44fiZE1czgn05W7vjZTPAgkx/0tyb+Ifd/wB9dlkYMhHWyktf1VhLPggEVLaVH3eNyNkylAps8rbMXwtuQX7s14FtMjATNa3a+oEwhiGqMNinHH69c5Hi/C9t7iTYnnp0o+RETs8kyrPTBEmDTDWeNHFBSxBCCWrZVul2IfajaHXBytTSPW6SS3BdFcr0Oqb5gcsraTxINrw1bhjqSBvby2W+yf12wTNl/Wc6ULOMGZNN+VfkNa9DVvbYreFmdGE/LyBD+45ANUHX+XZyzvSmaZQUJaU0nx+CVxsasG1RKf3NFTTN/jkL08rdXEjhRSY/LNW+Wfq1ojaeMuil6jMfcO6F2GAdetu1wXbmqOkTreaEIj3Lb
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: storage-creds-secret
      namespace: minio-blahcloud
    type: Opaque

