apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048deployment
  namespace: "2048-game"
spec:
  selector:
    matchLabels:
      app: "2048"
  replicas: 2
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      containers:
      - image: harbor.blah.cloud/mylesagray/doge2048:latest
        name: "2048"
        ports:
        - containerPort: 80