apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: oil-monitor
  name: oil-monitor
  namespace: oil-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: oil-monitor
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oil-monitor
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: boilerjuice-creds
        image: ghcr.io/mylesagray/boilerjuice-tank:0bff159
        name: api-server
        ports:
        - containerPort: 8080