apiVersion: v1
kind: Service
metadata:
  name: oil-monitor
  namespace: oil-monitor
spec:
  selector:
    app: oil-monitor
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080