apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: fluent-bit
  name: oil-monitor
  namespace: oil-monitor
spec:
  endpoints:
  - path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - oil-monitor
  selector:
    matchLabels:
      app.kubernetes.io/name: oil-monitor
