apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-auth
  namespace: influxdb
spec:
  encryptedData:
    influxdb-password: AgB/R3DY39J8fEt3JTMa2uPoC/Cq6h7Ej/8opK00moNTYwpNiLmkdJ/NwbYdB7Dk5M7OVLB8nWPuZrZRdwPFFKjidvtAQzfibQF2HOvVnFeOvx6KoigiVkCJb+K8SHHyduYk0/jBxF4ceEeR8wJrqOA0CgbwPTjaaLkURFqWiA2w5P3sQ15i4SXeiwwwXyHhkOaLADrj0YNXP8ythQaqTTR+MGmshZnxWuxF0bnT3n1jUnnUFWb0MAH3JSMs62yyBUNxr5TXj+6GnwJwMpI53LK7dWb5p3SKPTbtIEH0rYfUnjxjPrbu3hpUY33zUSUEqUdDhAJNuU6PVntYEtClxUwYlxdorvLgK4K4EWdDmXKU+8n9zzI4Zg5W4xTJ7ee5nW95cVFczJUCk5AjPvo9hnmEG1mJzFGGSYnwMOhHBKROu3qVPSwLkeMLE9c97IfUDOmPePuBvTuu7mmcjhseAGRjnf+K6+UlYHc5jGS1EZ+ERj5k+gN9XlH/IA3RQDqNxqpejVuP7s+Q8LqD/uy4LKO8irGnXioYvJOYDUeoZlyV+nMDhxJiy6RS5/xydIkr1DkLF2wfaBxTKQuX5yx/rnXnvDwmi7OvknqmzVMwXHRvO4Z9Nxnxs6ghrJN2v4BJQwhFE+oXukDhKstQw3ysfHp1aMBJo8w/IzcE5liPN78pBOO3pl3WL4vPsdpw5TCyGiwR393DpCxiZ0Kd
    influxdb-user: AgBoZvo0hwgA3goNDL1nhKmOgAZbuWUxPRpDAzYAw2NmEQlddQn2H8+41CjyPGlva4Qy8EUHo1KyuFV22G4ebe9U1g1aEsNKeoJ6/BOFeYx8WpRp3SgWIBYwzC77oEKOQPF/DKHe419UiL5B9dhOotcBgsz8Bzj+PsL3Gjm80h8MWAdj6SJnNuUw/rXHcbKjtVvtwy4DTjPSSzdivnfLMT7j/LIecwTbjQNRCrc51csMs6iLcCyvCRtHo0yrtbzTV1j+/+0sDuRpMjrQROYt+skpCb6vq456NZ2B/mGk7SJ2MtYIO4VaUHrW/f+2QJVWtuL82iPktb9z39T8YuCIdXOBjYZQpFn7Zx1316hnw4EvqPEEfH3rCcFFtbEBsNd8ngicXUUxnZJs2sBY++O6fu4PZEzm3hDrJ7Ffe6QmoxZpu38VeqOHziUBold6t8jussWS0mugFeVCSouexvoAd7VNr8DWsSEyPBfgjlwxdBWdIVwkIsJV9+njTCjRRbzOwLamSvCtqNBd0qZ0GkWA/w8kjgOUYP60hCZ6BlzKcozDqVH+bVvskr30ZvPPLGrM94dYD1ATUtww6Ct46wmGT73iCPh95kRiw8MNMkIJndBuLxk0MenFxz943UpWhdjaKN6XO5pMKM3PXBFcV9VZxGv4NL/pW5g2FhstX52JpAPGkk90lPxNX2vaBKx77G1D6Ej0aDj/3w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: influxdb-auth
      namespace: influxdb
    type: Opaque

