apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-minio
  namespace: minio
spec:
  encryptedData:
    accesskey: AgAQejW+QpwCDQ80AC0tkbaisk0e9WbPfobYqWEgQeMTMdFB9Yny6GGIeI/eTq3zOqv46z5iHhsbV246OKm4HVy0/AFQ8kaRV+P5k/s1BGvdkWaTvFc76cZGRS4crq8+YfofzBP1pVM+NLE4Ky0fiat7QeYo7I5DdUFRKQ2wGn2+5Gn68cqgmuxt1PC4BReXEeYACQhTk03I/nKlEdRca5dfdMzZep97O9lB+ChoyCN0JaH1AD7OML1Xjfpxec+Qz7jAPFtirxRhrb3lDG36q1L9KtwGSiIB0tnkJTMKvHLyBTS/uz9yDWEEL5WKBim92jOgv9PddDtrHmaFTYd5JqbzDS6cgekRQpuiE5vMFKLXiALeszWsbw15Y8dXYh8MPo7Bgcx4/I93FMrlFaWPrqj4zACSS8s6G5DmoYamiOUfaMMA7P3lsWE46arUutudtEluubgUsrxiIM00ElEx9M648A6XSuWExhxSFKAz1MsDUgNp003NxJDGZtmpbJInQGE/oexOxi5nLz1MyO6aGrVUIAT+sv4VjfNBWNT/mmT95Jz6P0vMbO/01naiCcIpcgmAlwQBtDcGgCXonHEdBPBmhAO9mU/W/C6mSvFasIhwIEfVrkBX+s8YYf7X1bPPGK4y57Nip+edn7h3+TDVk3YlUtNKI+gtFlcMHmqzKUghQbpTHhZm4PrqebxIq7djHsdpBeixP/4S00543133b8unsRKoSw==
    secretkey: AgA5ZRvfS+3HDBJNo/ntmBWvebm4q0gT3BU84Brw1fgG3Fpdb7ktkK6hwGnjkGBoiHFA9a8z/xr/PTDUsRuj9y7mdXwOsQggkywakApbiMPUJz5JZgfGg6mdvjunec4TIaoYoOdPv98KqogVrZM2PrdVjrMEEXzSYrYWhUWg2dE79iNX5ocD30RTF9TnFgy8CdOqP2Mc2gjDXgcpjGVIXSsLIam1bFSLSRMGGmCxpEyCmy1Owav4Fvam35Lht4hSU4GRSHLLN2tURj6hoOM6UAi49CuEpCOhWtF0fGtRKDMK+VHNpWH1/mMFcXWBMx+OcjxFc0/Bg2/kq1LePBlJXS2xaGM9bIpUxCsgbeYzRKb4F84bnW9qNhWThgsEtfwl5hcJYhipoCbTt8v5Ej08BtRNFTycBkxWwdaTqNiDiz9tDI1oUQ0PQ/shngQb2IaHhPRzVYXqHb+LFst8zK6ZbPGlEGnOwBrtIc0BhA2snCmgnI39CK7BphWb9QbDUlySOsFq2+ivRExlWVDcRehiN51dUqnxRer1Ogd8ASFZEVJfy84xONUcSDoTszc96CM+gSLNWnzdHWkAWQdf7CVfiKVUWeKSi5ViBr2BPFeESFR0poDtpRdXPYVK3xEQ+yhJR4JhOkZc633rOOTq/KNITdUN8CazlIpIrUuNiZwUgU9MQG5IkWiL1YAeRm1KCCq021RT27/n5dqQp3F/hC8XjjMUYxc4xFBX3rdf2HpcA0HF8+VyV2iGjoad
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app: minio
        argocd.argoproj.io/instance: argocd-workflows
      name: argo-workflows-minio
      namespace: minio
    type: Opaque

