external-dns:
  rbac:
    create: true
  crd:
    create: true
  metrics:
    enabled: true
  image:
    registry: k8s.gcr.io
    repository: external-dns/external-dns
    tag: v0.9.0
  provider: rfc2136
  rfc2136:
    host: "192.168.1.20"
    port: 53
    zone: "apps.blah.cloud"
    tsigSecret: "z/TzM3deQjnLQWDfrX887eGIfQAYoHQozZUFxJZPUixubKiFOTlsc24KaxRGEKhe4GbG/jXSk5uzthYpUGoMgQ=="
    tsigSecretAlg: hmac-md5
    tsigKeyname: external-dns
    tsigAxfr: true
  txtOwnerId: rak8s
  logLevel: info
  logFormat: json
  policy: sync