external-dns:
  rbac:
    create: true
  crd:
    create: true
  metrics:
    enabled: true
  image:
    registry: k8s.gcr.io
    repository: external-dns/external-dns
    tag: v0.9.0
  provider: rfc2136
  rfc2136:
    host: "192.168.1.20"
    port: 53
    zone: "apps.blah.cloud"
    tsigSecret: "AHyWUWLZ0GxSydCHjjo6RNoyjHDQk1nbCTkvqMNBgUi3YYssNUNJdHerpF+Ff3lufwSVNOWjDqy8P/Evdwi0QA=="
    tsigSecretAlg: hmac-sha512
    tsigKeyname: other
    tsigAxfr: true
  txtOwnerId: rak8s
  logLevel: info
  logFormat: json
  policy: sync